// GENERATED by game-builder (node game-builder/src/cli.mjs gen-frontend).
// Source of truth: game-builder/config/<game>.config.json. Do not edit by hand.
import type { RawSymbol } from './types';

export const GEN_NUM_REELS = 5;
export const GEN_NUM_ROWS: number[] = [4,4,4,4,4];
export const GEN_SYMBOL_SIZE = 140;
export const GEN_REEL_PADDING = 0.53;
export const GEN_HIGH_SYMBOLS = ["H1","H2","H3","H4","H5"];

const FILL_POOL = ["H1","H2","H3","H4","H5","L1","L2","L3","L4","L5"];

// Build a deterministic starting board: numRows[reel] visible + top/bottom
// padding (2 extra entries per reel), matching the engine's padded strips.
export function buildInitialBoard(): RawSymbol[][] {
	return GEN_NUM_ROWS.map((rows, reel) => {
		const total = rows + 2;
		const out: RawSymbol[] = [];
		for (let i = 0; i < total; i++) {
			out.push({ name: FILL_POOL[(reel * 3 + i) % FILL_POOL.length] });
		}
		return out;
	});
}
