// GENERATED by game-builder (node game-builder/src/cli.mjs gen-frontend).
// Source of truth: game-builder/config/<game>.config.json. Do not edit by hand.
export default {
	providerName: 'dramastudios',
	gameName: 'madam_mirror',
	gameID: '0_1_madam_mirror',
	rtp: 0.965,
	numReels: 5,
	numRows: [4,4,4,4,4],
	betModes: {
		base: {
			cost: 1.0,
			feature: true,
			buyBonus: false,
			rtp: 0.965,
			max_win: 30000,
		},
		bonus1: {
			cost: 100.0,
			feature: false,
			buyBonus: true,
			rtp: 0.965,
			max_win: 30000,
		},
		bonus2: {
			cost: 400.0,
			feature: false,
			buyBonus: true,
			rtp: 0.965,
			max_win: 30000,
		},
		bonus3: {
			cost: 1000.0,
			feature: false,
			buyBonus: true,
			rtp: 0.965,
			max_win: 30000,
		},
	},
	symbols: {
		W: {
			paytable: null,
			special_properties: ["wild"],
		},
		HM: {
			paytable: null,
			special_properties: ["mirror"],
		},
		ME: {
			paytable: null,
			special_properties: ["eye"],
		},
		S: {
			paytable: null,
			special_properties: ["scatter"],
		},
		H1: {
			paytable: [{ '5': 10 }, { '4': 3 }, { '3': 1 }],
		},
		H2: {
			paytable: [{ '5': 5 }, { '4': 1.5 }, { '3': 0.6 }],
		},
		H3: {
			paytable: [{ '5': 4 }, { '4': 1.2 }, { '3': 0.5 }],
		},
		H4: {
			paytable: [{ '5': 3 }, { '4': 1 }, { '3': 0.4 }],
		},
		H5: {
			paytable: [{ '5': 2.5 }, { '4': 0.8 }, { '3': 0.3 }],
		},
		L1: {
			paytable: [{ '5': 1.2 }, { '4': 0.4 }, { '3': 0.2 }],
		},
		L2: {
			paytable: [{ '5': 1.2 }, { '4': 0.4 }, { '3': 0.2 }],
		},
		L3: {
			paytable: [{ '5': 0.8 }, { '4': 0.3 }, { '3': 0.1 }],
		},
		L4: {
			paytable: [{ '5': 0.8 }, { '4': 0.3 }, { '3': 0.1 }],
		},
		L5: {
			paytable: [{ '5': 0.8 }, { '4': 0.3 }, { '3': 0.1 }],
		},
	},
	paddingReels: {
		basegame: '',
		freegame: '',
		superspingame: '',
	},
};
