// GENERATED by game-builder (node game-builder/src/cli.mjs gen-frontend).
// Source of truth: game-builder/config/<game>.config.json. Do not edit by hand.

export const GEN_FX: Record<string, any> = {
	"splitTelegraph": {
		"label": "Split Telegraph",
		"desc": "Volley of tiny glass shards shooting from the mirror into the cells it is about to split.",
		"shardsPerTarget": 8,
		"durationMs": 340,
		"colors": [
			"0xd8ecff",
			"0xc9a8ff"
		]
	},
	"splitShatter": {
		"label": "Split Shatter",
		"desc": "The cracked pane bursts into flying glass shards when the split resolves.",
		"shardsPerCell": 14,
		"durationMs": 650,
		"colors": [
			"0xd8ecff",
			"0xb887ff"
		]
	},
	"mirrorBreak": {
		"label": "Mirror Break",
		"desc": "Cracked-glass pane pop-in and hold before the shatter.",
		"popMs": 130,
		"holdMs": 420
	},
	"winLightning": {
		"label": "Mega-Win Lightning",
		"desc": "Thunder bolts + prismatic burst over the board when a win reaches megaWinMultiplier x bet (max-win celebration).",
		"megaWinMultiplier": 8685,
		"hue": 360,
		"size": 2,
		"lightningMs": 1400,
		"prismaticMs": 4570,
		"maxExtraBolts": 40,
		"prismaticIntensity": 5,
		"prismaticSpeed": 1,
		"colors": [
			"#A855F7",
			"#7C3AED",
			"#6366F1"
		]
	},
	"winSweep": {
		"label": "Win Sweep",
		"desc": "Plasma surge sweeping left-to-right across the connecting symbols of a win.",
		"reelStagger": 0.22,
		"baseMs": 550,
		"perReelMs": 130
	},
	"winDim": {
		"label": "Win Dim",
		"desc": "Darkens every non-winning cell so the winning symbols pop.",
		"dimAlpha": 0.78
	},
	"apparition": {
		"label": "Apparition Win Grow",
		"desc": "Haunted apparition cells scale up when they are part of a win.",
		"winGrow": 1.1
	},
	"splitAnimation": {
		"label": "Split Animation",
		"desc": "The actual split: blade cut sweep, hit-stop seam flare, detonation (flash/shockwave/sparks), panes snapping apart with overshoot, pulse punch and board kick.",
		"cutMs": 140,
		"cutStagger": 0.15,
		"flareInMs": 20,
		"flareOutMs": 150,
		"detonationMs": 300,
		"paneSnapMs": 130,
		"pulseScale": 1.45,
		"pulseMs": 420,
		"shakeBase": 10,
		"shakePerCell": 2.5,
		"shakeMax": 18,
		"shakeMs": 240,
		"bladeSparks": 4,
		"seamSparks": 6
	},
	"plasmaLiner": {
		"label": "Win Liner Fire",
		"desc": "Green plasma fire tracing the merged outer contour of the winning combination, igniting left-to-right.",
		"igniteStagger": 0.09,
		"igniteFlash": 0.24,
		"cornerRadius": 15,
		"fadeInMs": 100,
		"fadeOutMs": 260,
		"flameHeightMin": 4,
		"flameHeightMax": 18,
		"lickScale": 2.8,
		"lickEvery": 7,
		"upBias": 0.55
	},
	"framePlasma": {
		"label": "Frame Fire",
		"desc": "Purple flame ring licking off the board-frame perimeter during free spins.",
		"envelopeMs": 420,
		"flameHeightMin": 7,
		"flameHeightMax": 30,
		"lickScale": 2.5,
		"lickEvery": 7,
		"upBias": 0.5,
		"inset": 5,
		"marginScale": 0.16
	}
};

/** Read a numeric FX param with a fallback default. */
export function fxNum(effect: string, key: string, fallback: number): number {
	const v = GEN_FX?.[effect]?.[key];
	return typeof v === 'number' && Number.isFinite(v) ? v : fallback;
}

/** Read a string-array FX param (e.g. CSS colors) with a fallback default. */
export function fxArr(effect: string, key: string, fallback: string[]): string[] {
	const v = GEN_FX?.[effect]?.[key];
	return Array.isArray(v) && v.length ? v.map(String) : fallback;
}

/** Read a color-array FX param as pixi numeric colors (accepts "0xRRGGBB" / "#RRGGBB"). */
export function fxColors(effect: string, key: string, fallback: number[]): number[] {
	const v = GEN_FX?.[effect]?.[key];
	if (!Array.isArray(v) || !v.length) return fallback;
	const nums = v.map((c: unknown) => Number(String(c).replace('#', '0x')));
	return nums.every((n: number) => Number.isFinite(n)) ? nums : fallback;
}
