// GENERATED by game-builder (node game-builder/src/cli.mjs gen-frontend).
// Source of truth: game-builder/config/<game>.config.json. Do not edit by hand.

export const GEN_HUD: Record<string, any> = {
	"colors": {
		"accent": "#ffc12e",
		"text": "#f0e6d0",
		"spinButton": "#f7bb0f",
		"turbo": "#ffb400",
		"panelFill": "#10161d",
		"panelStroke": "#2a3542",
		"stepper": "#1c2732",
		"balanceText": "#f0e6d0",
		"betText": "#f0e6d0"
	},
	"logo": {
		"studio": "mirror/logo.png",
		"buyBonus": "packages/components-ui-pixi/src/assets/buyBonusLogoData.ts#BUY_BONUS_LOGO_DATA_URL"
	}
};

/** Read a HUD colour token as a pixi numeric colour (accepts "#RRGGBB" / "0xRRGGBB"). */
export function hudColor(key: string, fallback: number): number {
	const v = GEN_HUD?.colors?.[key];
	if (typeof v !== 'string' || !v) return fallback;
	const n = Number(v.replace('#', '0x'));
	return Number.isFinite(n) ? n : fallback;
}

/** Read a numeric HUD token (e.g. shape.buttonRadius) with a fallback default. */
export function hudNum(group: string, key: string, fallback: number): number {
	const v = GEN_HUD?.[group]?.[key];
	return typeof v === 'number' && Number.isFinite(v) ? v : fallback;
}

/** Read a HUD asset path/reference string (e.g. logo.studio) with a fallback. */
export function hudPath(group: string, key: string, fallback: string): string {
	const v = GEN_HUD?.[group]?.[key];
	return typeof v === 'string' && v ? v : fallback;
}
