window.VFX_CATALOG = {
  "packs": [
    {
      "id": "riveted-plank-door-swing",
      "title": "Riveted Plank Door Swing",
      "sheet": "riveted-plank-door-swing/riveted-plank-door-swing-sheet.png",
      "partsDir": "riveted-plank-door-swing/parts",
      "spine": "riveted-plank-door-swing/spine/skeleton.json",
      "fps": 16,
      "blend": "normal",
      "pivot": "bottom",
      "kind": "sequence",
      "frameCount": 9,
      "peakFrame": "frame_01.png",
      "frames": [
        "frame_01.png",
        "frame_02.png",
        "frame_03.png",
        "frame_04.png",
        "frame_05.png",
        "frame_06.png",
        "frame_07.png",
        "frame_08.png",
        "frame_09.png"
      ],
      "sheetSize": {
        "w": 3072,
        "h": 2048
      },
      "speedCurve": "linear",
      "framePhases": [
        "idle",
        "idle",
        "idle",
        "idle",
        "idle",
        "idle",
        "idle",
        "idle",
        "idle"
      ],
      "frameScales": [
        1.0,
        1.0,
        1.0,
        1.0,
        1.0,
        1.0,
        1.0,
        1.0,
        1.0
      ],
      "frameDurations": [
        0.0625,
        0.0625,
        0.0625,
        0.0625,
        0.0625,
        0.0625,
        0.0625,
        0.0625,
        0.0625
      ]
    },
    {
      "id": "saloon-door-swing",
      "title": "Saloon Door Swing",
      "sheet": "saloon-door-swing/saloon-door-swing-sheet.png",
      "partsDir": "saloon-door-swing/parts",
      "spine": "saloon-door-swing/spine/skeleton.json",
      "fps": 14,
      "blend": "normal",
      "pivot": "bottom",
      "kind": "sequence",
      "frameCount": 16,
      "peakFrame": "frame_01.png",
      "frames": [
        "frame_01.png",
        "frame_02.png",
        "frame_03.png",
        "frame_04.png",
        "frame_05.png",
        "frame_06.png",
        "frame_07.png",
        "frame_08.png",
        "frame_09.png",
        "frame_10.png",
        "frame_11.png",
        "frame_12.png",
        "frame_13.png",
        "frame_14.png",
        "frame_15.png",
        "frame_16.png"
      ],
      "sheetSize": {
        "w": 1536,
        "h": 1024
      },
      "speedCurve": "easeOut",
      "framePhases": [
        "strike",
        "strike",
        "strike",
        "strike",
        "strike",
        "strike",
        "strike",
        "strike",
        "recover",
        "recover",
        "recover",
        "recover",
        "recover",
        "recover",
        "recover",
        "recover"
      ],
      "frameScales": [
        0.55,
        0.5967,
        0.6433,
        0.69,
        0.7367,
        0.7833,
        0.83,
        0.8767,
        0.9233,
        0.97,
        1.0167,
        1.0633,
        1.11,
        1.1567,
        1.2033,
        1.25
      ],
      "frameDurations": [
        0.0393,
        0.0426,
        0.046,
        0.0493,
        0.0526,
        0.056,
        0.0593,
        0.0626,
        0.066,
        0.0693,
        0.0726,
        0.076,
        0.0793,
        0.0826,
        0.086,
        0.0893
      ]
    }
  ]
};
