// Isolated feature books generated by the math engine
// (math-sdk/games/0_3_tombstone_reborn/make_feature_story_books.py).
import type { BookEvent } from '../../game/typesBookEvent';
import generated from './feature_demo_books.generated.json';

export type DemoBook = {
	label: string;
	mode: string;
	payoutX: number;
	events: BookEvent[];
};

export const FEATURE_DEMO_BOOKS = generated as DemoBook[];
