// Showcase books generated by the math engine
// (math-sdk/games/0_3_tombstone_reborn/make_showcase_books.py). Each book is a
// full single-spin event stream: reveal -> boardSpecials -> feature events ->
// winInfo/setWin -> finalWin.
import showcase from '../../showcase.generated.json';
import { FEATURE_DEMO_BOOKS } from './feature_demo_books';
import type { DemoBook } from './feature_demo_books';
// REAL max-win books curated from the simulated library
// (math-sdk/games/0_3_tombstone_reborn/make_maxwin_story_books.py).
import maxwinGenerated from './maxwin_books.generated.json';

const MAXWIN_BOOKS = maxwinGenerated as DemoBook[];

export type ShowcaseBook = {
	label: string;
	mode: string;
	payoutX: number;
	events: unknown[];
};

const books = showcase as unknown as ShowcaseBook[];

export const bookByLabel = (label: string) => {
	const maxwin = MAXWIN_BOOKS.find((book) => book.label === label);
	if (maxwin) {
		return {
			id: 950 + MAXWIN_BOOKS.indexOf(maxwin),
			payoutMultiplier: maxwin.payoutX,
			events: maxwin.events,
			mode: maxwin.mode,
		};
	}
	const demo = FEATURE_DEMO_BOOKS.find((book) => book.label === label);
	if (demo) {
		return {
			id: 900 + FEATURE_DEMO_BOOKS.indexOf(demo),
			payoutMultiplier: demo.payoutX,
			events: demo.events,
			mode: demo.mode,
		};
	}
	const index = books.findIndex((book) => book.label === label);
	if (index < 0) throw new Error(`no showcase book labelled "${label}"`);
	const book = books[index];
	return { id: index, payoutMultiplier: book.payoutX, events: book.events, mode: book.mode };
};

export default books;
