// Showcase books generated by the math engine
// (math-sdk/games/0_3_tombstone_reborn/make_showcase_books.py). Each book is a
// full single-spin event stream: reveal -> specialBar -> feature events ->
// winInfo/setWin -> finalWin.
import showcase from '../../showcase.generated.json';

export type ShowcaseBook = {
	label: string;
	mode: string;
	payoutX: number;
	events: unknown[];
};

const books = showcase as unknown as ShowcaseBook[];

export const bookByLabel = (label: string) => {
	const index = books.findIndex((book) => book.label === label);
	if (index < 0) throw new Error(`no showcase book labelled "${label}"`);
	const book = books[index];
	return { id: index, payoutMultiplier: book.payoutX, events: book.events };
};

export default books;
