"""THE WHITE ROOM - GENERATED by game-builder (do not edit by hand).

Regenerate: node game-builder/src/cli.mjs gen-math the_white_room
Source of truth: game-builder/config/the_white_room.config.json
"""

import os
from src.config.config import Config
from src.config.distributions import Distribution
from src.config.betmode import BetMode


class GameConfig(Config):
    """Game specific configuration class."""

    _instance = None

    def __new__(cls):
        if cls._instance is None:
            cls._instance = super().__new__(cls)
        return cls._instance

    def __init__(self):
        super().__init__()
        self.game_id = "0_2_the_white_room"
        self.provider_name = "dramastudios"
        self.game_name = "the_white_room"
        self.provider_number = 0
        self.working_name = "THE WHITE ROOM"
        self.wincap = 30000.0
        self.win_type = "ways"
        self.rtp = 0.965
        self.construct_paths()

        # Game Dimensions
        self.num_reels = 5
        self.num_rows = [4, 3, 2, 3, 4]

        # 6-/7-of-a-kind entries support the extended board: when premium symbols
        # drop into the LEFT/RIGHT locked-slot columns the board grows from 5 to
        # up to 7 reels, so ways wins can connect across 6 or 7 reels. The engine
        # (src/calculations/ways.py) already counts `kind` across however many
        # reels the board has - it only needs these paytable rows to pay 6/7.
        # NOTE: 6/7 values are placeholders and MUST be re-optimized once the
        # premium-drop mechanic is live (they never fire on the current 5-reel
        # board, so they don't affect current RTP).
        self.paytable = {
            (7, "H1"): 100, (6, "H1"): 30, (5, "H1"): 10, (4, "H1"): 3, (3, "H1"): 1,
            (7, "H2"): 50, (6, "H2"): 15, (5, "H2"): 5, (4, "H2"): 1.5, (3, "H2"): 0.6,
            (7, "H3"): 40, (6, "H3"): 12, (5, "H3"): 4, (4, "H3"): 1.2, (3, "H3"): 0.5,
            (7, "H4"): 30, (6, "H4"): 9, (5, "H4"): 3, (4, "H4"): 1, (3, "H4"): 0.4,
            (7, "H5"): 25, (6, "H5"): 7.5, (5, "H5"): 2.5, (4, "H5"): 0.8, (3, "H5"): 0.3,
            (7, "L1"): 8, (6, "L1"): 3, (5, "L1"): 1.2, (4, "L1"): 0.4, (3, "L1"): 0.2,
            (7, "L2"): 8, (6, "L2"): 3, (5, "L2"): 1.2, (4, "L2"): 0.4, (3, "L2"): 0.2,
            (7, "L3"): 6, (6, "L3"): 2, (5, "L3"): 0.8, (4, "L3"): 0.3, (3, "L3"): 0.1,
            (7, "L4"): 6, (6, "L4"): 2, (5, "L4"): 0.8, (4, "L4"): 0.3, (3, "L4"): 0.1,
            (7, "L5"): 6, (6, "L5"): 2, (5, "L5"): 0.8, (4, "L5"): 0.3, (3, "L5"): 0.1,
        }

        self.include_padding = True
        self.special_symbols = {"wild": ["W"], "scatter": ["S"], "multiplier": []}

        self.freespin_triggers = {
            self.basegame_type: {3: 8, 4: 10, 5: 12},
            self.freegame_type: {2: 3, 3: 3, 4: 3, 5: 3},
        }
        self.anticipation_triggers = {
            self.basegame_type: min(self.freespin_triggers[self.basegame_type].keys()) - 1,
            self.freegame_type: min(self.freespin_triggers[self.freegame_type].keys()) - 1,
        }

        # The 3 bonus levels differ only by how many locked-slot groups unlock
        # (see unlocked_slot_config.unlock_by_level); the old per-level mirror /
        # fracture / lifetime / stacking rules were removed with the split feature.
        self.bonus_levels = {1: {"name": "THE_INTAKE"}, 2: {"name": "HER_SIDE"}, 3: {"name": "WHITEOUT"}}
        self.scatter_to_level = {3: 1, 4: 2, 5: 3}

        # Legacy Cell Seal (full-reel wild from a high symbol) is retired - it is
        # repurposed into WILD REEL below. Kept disabled for reference.
        self.cell_seal_config = {"enabled": False, "label": "Cell Seal", "seal_harden_label": "Seal Hardens", "symbols": ["H1", "H2", "H3", "H4", "H5"], "expand_as_wild": True, "probability": {self.basegame_type: 0.0, self.freegame_type: 0.0}, "reel_count_weights": {1: 94, 2: 5, 3: 0.8, 4: 0.15, 5: 0.05}, "ways_weights": {4: 88, 5: 9, 6: 2.5, 8: 0.5}, "ways_cap": {self.basegame_type: 6, self.freegame_type: 8}, "seal_harden": {"enabled": False, "bump": 1, "max_bumps_per_spin": 2}}

        # WILD REEL (repurposed Cell Seal): a special symbol can land in the bottom
        # locked slot under each middle reel (1, 2, 3). Every bottom-slot symbol
        # turns its reel into a rising wild - the reel extends up to `target_rows`
        # (4), pushing the existing symbols up and filling the new bottom cell(s)
        # with WILD carrying a random multiplier (counted by the ways engine).
        # Each middle reel rolls independently, so the number of wild reels equals
        # the number of bottom-slot symbols shown.
        # NOTE: probability/mult weights are placeholders and MUST be re-optimized.
        self.wild_reel_config = {
            "enabled": True,
            "label": "Wild Reel",
            "eligible_reels": [1, 2, 3],
            "target_rows": 4,
            "probability": {self.basegame_type: 0.03, self.freegame_type: 0.05},
            "mult_weights": {1: 55, 2: 25, 3: 12, 5: 6, 10: 2},
        }

        # UNLOCKED SLOTS (bonus-only board expansion). During free spins the
        # reserved locked slots open up progressively by bonus level:
        #   level 1 (THE_INTAKE): BOTTOM slots (under middle reels 1,2,3)
        #   level 2 (HER_SIDE)  : BOTTOM + RIGHT column
        #   level 3 (WHITEOUT)  : BOTTOM + RIGHT + LEFT columns  (full 7-wide)
        # Each unlocked slot independently rolls a PREMIUM (H1-H5), a WILD, or
        # stays EMPTY, re-rolled every free spin. Filled slots become real board
        # cells so the ways engine counts them: the RIGHT column is appended as
        # an extra reel (=> up to 6-of-a-kind), the LEFT column as a further reel
        # (=> up to 7-of-a-kind), and BOTTOM premiums extend their middle reel.
        # A WILD in a bottom slot still RISES into its reel (the Wild Reel above).
        # NOTE: all weights are placeholders and MUST be re-optimized - the extra
        # cells add wins, so RTP has to be re-balanced once this mechanic is live.
        self.unlocked_slot_config = {
            "enabled": True,
            "label": "Unlocked Slots",
            "unlock_by_level": {
                1: ["bottom"],
                2: ["bottom", "right"],
                3: ["bottom", "right", "left"],
            },
            "bottom_reels": [1, 2, 3],
            "side_rows": 3,
            # per-slot independent content roll (BONUS: unlocked cells every spin).
            # Now also rolls the 3 new feature symbols (stretch / split / clone).
            # An UNLOCKED cell is NEVER empty: every cell is guaranteed at least a
            # premium, with a chance of a wild or a feature instead.
            "content_weights": {"premium": 72, "wild": 10, "stretch": 8, "split": 6, "clone": 4},
            # SIDE columns (right / left) are ALSO feature cells: they roll premiums,
            # wilds and the board-wide features CLONE / SPLIT (Stretch stays a
            # vertical middle-reel feature, so it's not in the side table). Never empty.
            "content_weights_side": {"premium": 72, "wild": 10, "split": 10, "clone": 8},
            # BASE GAME: cells are LOCKED; a special symbol only very rarely drops
            # and unlocks THAT one cell. Overwhelmingly "empty" (stays locked).
            "content_weights_base": {"empty": 990, "wild": 3, "stretch": 3, "split": 2, "clone": 2},
            # which premium lands when a slot rolls "premium"
            "premium_weights": {"H1": 6, "H2": 10, "H3": 14, "H4": 20, "H5": 26},
            # multiplier carried by a slot WILD (matches Wild Reel style)
            "mult_weights": {1: 58, 2: 24, 3: 11, 5: 5, 10: 2},
        }

        # STRETCH (feature symbol): stretches its own reel and gives every symbol on
        # it a weighted-random x-ways multiplier (volatile: mostly 1-3, long tail to
        # 10). count_board_ways counts multiplier=m as m symbols on the reel, so the
        # reel's ways = sum of its multipliers, capped by ways_cap.
        # NOTE: placeholder weights - re-optimize in the final sim.
        self.stretch_config = {
            "label": "Stretch",
            # NORMAL reel: every symbol on the reel gets a weighted-random x-ways
            # multiplier (volatile: mostly 1-3, long tail to 10). The reel's total
            # ways (sum of these) is capped by ways_cap.
            "ways_weights": {1: 40, 2: 26, 3: 15, 4: 8, 5: 5, 6: 3, 8: 2, 10: 1},
            "ways_cap": 500,
            # A STRETCH never converts its reel to wild any more: the card said
            # STRETCH but 22% of the time the result was indistinguishable from
            # the WILD card's column, which read as a bug. Only the WILD card
            # makes wild reels now.
            "wild_chance": 0.0,
        }

        # SPLIT (feature symbol): after wins are known, picks ONE winning symbol
        # type and ADDS a weighted +1..+10 ways to each of its winning cells,
        # so the ways engine counts extra copies (volatile). Does nothing on a
        # losing spin. NOTE: placeholder weights - re-optimize in the final sim.
        self.split_config = {
            "label": "Split",
            # ADDED to each affected cell's ways (split is additive, never a
            # multiplier): a split grants +1 to +10 ways, mostly small.
            "split_weights": {1: 38, 2: 26, 3: 15, 4: 9, 5: 5, 6: 3, 7: 2, 8: 1, 9: 1, 10: 1},
        }

        # CLONE (feature symbol): picks ONE symbol type present on the board
        # (source_weights bias the pick toward common/low symbols) and converts
        # every copy of it into a weighted-random PREMIUM (H1-H5).
        # NOTE: placeholder weights - re-optimize in the final sim.
        self.clone_config = {
            "label": "Clone",
            "source_weights": {
                "L1": 10, "L2": 10, "L3": 12, "L4": 12, "L5": 14,
                "H5": 12, "H4": 10, "H3": 8, "H2": 7, "H1": 5,
            },
            "premium_weights": {"H1": 6, "H2": 10, "H3": 14, "H4": 20, "H5": 26},
        }

        # Reels
        reels = {"BR0": "BR0.csv", "FR0": "FR0.csv", "FRWCAP": "FRWCAP.csv", "BRWCAP": "BRWCAP.csv"}
        self.reels = {}
        for r, fn in reels.items():
            self.reels[r] = self.read_reels_csv(os.path.join(self.reels_path, fn))

        self.padding_reels[self.basegame_type] = self.reels["BR0"]
        self.padding_reels[self.freegame_type] = self.reels["FR0"]

        def wincap_condition(scatter_triggers):
            return {
                "reel_weights": {self.basegame_type: {"BR0": 1}, self.freegame_type: {"FR0": 1, "FRWCAP": 8}},
                "force_wincap": True,
                "force_freegame": True,
                "scatter_triggers": scatter_triggers,
            }

        base_wincap_condition = {
            "reel_weights": {self.basegame_type: {"BRWCAP": 1}},
            "force_wincap": True,
            "force_freegame": False,
        }
        zero_condition = {"reel_weights": {self.basegame_type: {"BR0": 1}}, "force_wincap": False, "force_freegame": False}
        basegame_condition = {"reel_weights": {self.basegame_type: {"BR0": 1}}, "force_wincap": False, "force_freegame": False}

        def freegame_condition(scatter_triggers):
            return {
                "reel_weights": {self.basegame_type: {"BR0": 1}, self.freegame_type: {"FR0": 1}},
                "force_wincap": False,
                "force_freegame": True,
                "scatter_triggers": scatter_triggers,
            }

        mode_maxwin = 30000
        self.mode_rtps = {"base": 0.962, "ante": 0.962, "bonus1": 0.965, "bonus2": 0.966, "bonus3": 0.9665}

        def ante_condition(base_condition):
            condition = dict(base_condition)
            condition["force_scatter_reel"] = 0
            return condition

        self.bet_modes = [
            BetMode(
                name="base",
                cost=1.00,
                rtp=self.mode_rtps["base"],
                max_win=mode_maxwin,
                auto_close_disabled=False,
                is_feature=True,
                is_buybonus=False,
                distributions=[
                    Distribution(criteria="wincap", quota=0.001, win_criteria=mode_maxwin, conditions=base_wincap_condition),
                    Distribution(criteria="freegame", quota=0.08, conditions=freegame_condition({3: 100, 4: 25, 5: 6})),
                    Distribution(criteria="0", quota=0.549, win_criteria=0.0, conditions=zero_condition),
                    Distribution(criteria="basegame", quota=0.37, conditions=basegame_condition),
                ],
            ),
            BetMode(
                name="ante",
                cost=1.25,
                rtp=self.mode_rtps["ante"],
                max_win=mode_maxwin,
                auto_close_disabled=False,
                is_feature=True,
                is_buybonus=False,
                distributions=[
                    Distribution(criteria="wincap", quota=0.001, win_criteria=mode_maxwin, conditions=ante_condition(base_wincap_condition)),
                    Distribution(criteria="freegame", quota=0.14, conditions=ante_condition(freegame_condition({3: 100, 4: 25, 5: 6}))),
                    Distribution(criteria="0", quota=0.539, win_criteria=0.0, conditions=ante_condition(zero_condition)),
                    Distribution(criteria="basegame", quota=0.32, conditions=ante_condition(basegame_condition)),
                ],
            ),
            BetMode(
                name="bonus1",
                cost=100.00,
                rtp=self.mode_rtps["bonus1"],
                max_win=mode_maxwin,
                auto_close_disabled=False,
                is_feature=False,
                is_buybonus=True,
                distributions=[
                    Distribution(criteria="wincap", quota=0.001, win_criteria=mode_maxwin, conditions=wincap_condition({3: 1})),
                    Distribution(criteria="freegame", quota=0.999, conditions=freegame_condition({3: 1})),
                ],
            ),
            BetMode(
                name="bonus2",
                cost=400.00,
                rtp=self.mode_rtps["bonus2"],
                max_win=mode_maxwin,
                auto_close_disabled=False,
                is_feature=False,
                is_buybonus=True,
                distributions=[
                    Distribution(criteria="wincap", quota=0.001, win_criteria=mode_maxwin, conditions=wincap_condition({4: 1})),
                    Distribution(criteria="freegame", quota=0.999, conditions=freegame_condition({4: 1})),
                ],
            ),
            BetMode(
                name="bonus3",
                cost=1000.00,
                rtp=self.mode_rtps["bonus3"],
                max_win=mode_maxwin,
                auto_close_disabled=False,
                is_feature=False,
                is_buybonus=True,
                distributions=[
                    Distribution(criteria="wincap", quota=0.004, win_criteria=mode_maxwin, conditions=wincap_condition({5: 1})),
                    Distribution(criteria="freegame", quota=0.996, conditions=freegame_condition({5: 1})),
                ],
            )
        ]
