"""Optimizer-only pass for the local White Room build.

Books were already generated by run_local.py; this just runs the Rust
optimizer over the existing books and (re)writes the publish configs so the
mock RGS has index.json + lookup tables. Separated out so a failed optimizer
run (e.g. missing Cargo.toml) doesn't force re-simulating every mode.
"""

from gamestate import GameState
from game_config import GameConfig
from game_optimization import OptimizationSetup
from optimization_program.run_script import OptimizationExecution
from src.write_data.write_configs import generate_configs

if __name__ == "__main__":
    rust_threads = 16
    target_modes = ["base", "ante", "feature1", "feature2", "feature3", "bonus1", "bonus2", "bonus3"]

    config = GameConfig()
    gamestate = GameState(config)
    OptimizationSetup(config)

    generate_configs(gamestate)
    OptimizationExecution().run_all_modes(config, target_modes, rust_threads)
    generate_configs(gamestate)

    print("LOCAL OPT COMPLETE")
