"""Smoke: force Cell Seal + Seal Hardens paths and export FE showcase books.

Elevates probability only inside this script (does not mutate shipped config).
Writes:
  - library/books/books_cell_seal.json (math samples)
  - web-sdk/apps/ways/src/stories/data/cell_seal_math_books.ts (optional FE import)
"""

from __future__ import annotations

import json
import os
import sys

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..")))
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from gamestate import GameState
from game_config import GameConfig
from src.state.run_sims import create_books

HERE = os.path.dirname(os.path.abspath(__file__))
BOOKS_DIR = os.path.join(HERE, "library", "books")
WEB_OUT = os.path.abspath(
    os.path.join(HERE, "..", "..", "..", "web-sdk", "apps", "ways", "src", "stories", "data")
)
# Small elevated-prob sample only. Never point this at a full publish regen.
# create_books(compress=False) writes library/books/books_base.json — restore
# forces/configs from 0_1 afterward if you need the full force_record again.
NUM = {"base": 800}


def elevate_cell_seal(config: GameConfig):
    cfg = dict(config.cell_seal_config or {})
    cfg["enabled"] = True
    cfg["probability"] = {
        config.basegame_type: 0.55,
        config.freegame_type: 0.55,
    }
    # Bias multi-reel + joint with mirrors so Seal Hardens can fire
    cfg["reel_count_weights"] = {1: 40, 2: 35, 3: 15, 4: 7, 5: 3}
    config.cell_seal_config = cfg
    # Slightly elevate mirror chance so harden joint appears in samples
    mc = dict(config.mirror_config)
    mc["probability"] = {config.basegame_type: 0.45}
    config.mirror_config = mc


def main():
    config = GameConfig()
    elevate_cell_seal(config)
    gamestate = GameState(config)
    create_books(gamestate, config, dict(NUM), 80, 1, False, False)

    path = os.path.join(BOOKS_DIR, "books_base.json")
    with open(path, encoding="utf-8") as f:
        books = json.load(f)

    seal_books = [b for b in books if any(e.get("type") == "cellSeal" for e in b["events"])]
    harden_books = [b for b in books if any(e.get("type") == "sealHarden" for e in b["events"])]

    os.makedirs(BOOKS_DIR, exist_ok=True)
    out_json = os.path.join(BOOKS_DIR, "books_cell_seal.json")
    with open(out_json, "w", encoding="utf-8") as f:
        json.dump(seal_books[:40], f, indent=1)

    # Pick one clean single-seal + one harden sample for FE
    single = next(
        (
            b
            for b in seal_books
            if not any(e.get("type") == "sealHarden" for e in b["events"])
            and len(next(e for e in b["events"] if e["type"] == "cellSeal")["seals"]) == 1
        ),
        seal_books[0] if seal_books else None,
    )
    harden = harden_books[0] if harden_books else None

    samples = [b for b in (single, harden) if b]
    ts_path = os.path.join(WEB_OUT, "cell_seal_math_books.ts")
    with open(ts_path, "w", encoding="utf-8") as f:
        f.write(
            "// GENERATED by math-sdk/games/0_2_the_white_room/smoke_cell_seal.py\n"
            "// Elevated-prob smoke samples for live Game path / Storybook.\n"
            "import type { BookEvent } from '../../game/typesBookEvent';\n\n"
            f"export default {json.dumps(samples, indent=1)} as {{ id: number; payoutMultiplier?: number; events: BookEvent[] }}[];\n"
        )

    print(
        json.dumps(
            {
                "ok": True,
                "totalBooks": len(books),
                "cellSealBooks": len(seal_books),
                "sealHardenBooks": len(harden_books),
                "outJson": out_json,
                "outTs": ts_path,
                "sampleIds": [b["id"] for b in samples],
            },
            indent=2,
        )
    )
    assert seal_books, "expected cellSeal events in elevated smoke"
    # Harden is probabilistic; warn but don't fail hard if joint rare in short run
    if not harden_books:
        print("WARN: no sealHarden in this smoke — authored Storybook book still covers FE path")


if __name__ == "__main__":
    main()
