// GENERATED by math-sdk/games/0_2_the_white_room/make_all_features_book.py
// ONE bonus spin where every feature fires: Unlocked Slots + Wild Reel +
// Stretch + Clone + Split, resolving into a win. Plays through the live Game.
import type { BookEvent } from '../../game/typesBookEvent';

type ShowcaseBook = { id: number; payoutMultiplier: number; events: BookEvent[] };

export const allFeaturesBook: ShowcaseBook =
	{
 "id": 11157,
 "payoutMultiplier": 8580,
 "events": [
  {
   "type": "bonusLevel",
   "level": 3,
   "name": "ALL FEATURES",
   "startHaunted": [],
   "index": 0
  },
  {
   "index": 1,
   "type": "reveal",
   "board": [
    [
     {
      "name": "L3"
     },
     {
      "name": "H1"
     },
     {
      "name": "L2"
     },
     {
      "name": "L5"
     },
     {
      "name": "L3"
     },
     {
      "name": "L5"
     }
    ],
    [
     {
      "name": "L2"
     },
     {
      "name": "H3"
     },
     {
      "name": "H3"
     },
     {
      "name": "H5"
     },
     {
      "name": "H5"
     }
    ],
    [
     {
      "name": "H2"
     },
     {
      "name": "H1"
     },
     {
      "name": "H4"
     },
     {
      "name": "H1"
     }
    ],
    [
     {
      "name": "L1"
     },
     {
      "name": "L3"
     },
     {
      "name": "H3"
     },
     {
      "name": "H4"
     },
     {
      "name": "L4"
     }
    ],
    [
     {
      "name": "H1"
     },
     {
      "name": "L4"
     },
     {
      "name": "L4"
     },
     {
      "name": "L2"
     },
     {
      "name": "L4"
     },
     {
      "name": "H5"
     }
    ]
   ],
   "paddingPositions": [
    144,
    24,
    166,
    180,
    201
   ],
   "gameType": "freegame",
   "anticipation": [
    0,
    0,
    0,
    0,
    0
   ]
  },
  {
   "index": 2,
   "type": "unlockedSlots",
   "label": "Unlocked Slots",
   "level": 3,
   "unlocked": [
    "bottom",
    "right",
    "left"
   ],
   "bottom": [],
   "sides": [
    {
     "side": "right",
     "reel": 5,
     "cells": [
      {
       "row": 1,
       "slotRow": 2,
       "name": "H4"
      }
     ]
    }
   ],
   "totalWays": 288
  },
  {
   "index": 3,
   "type": "wildReel",
   "label": "Wild Reel",
   "reels": [
    {
     "reel": 1,
     "baseRows": 3,
     "added": 1,
     "cells": [
      {
       "row": 4,
       "multiplier": 3
      }
     ]
    }
   ],
   "totalWays": 576
  },
  {
   "index": 4,
   "type": "wildReel",
   "label": "Wild Reel",
   "reels": [
    {
     "reel": 2,
     "baseRows": 2,
     "added": 2,
     "cells": [
      {
       "row": 3,
       "multiplier": 1
      },
      {
       "row": 4,
       "multiplier": 5
      }
     ]
    }
   ],
   "totalWays": 2304
  },
  {
   "index": 5,
   "type": "stretchReel",
   "label": "Stretch",
   "reels": [
    {
     "reel": 3,
     "mode": "normal",
     "baseRows": 3,
     "reelWays": 18,
     "cells": [
      {
       "row": 1,
       "multiplier": 3
      },
      {
       "row": 2,
       "multiplier": 5
      },
      {
       "row": 3,
       "multiplier": 10
      }
     ]
    }
   ],
   "totalWays": 13824
  },
  {
   "index": 6,
   "type": "cloneSymbol",
   "label": "Clone",
   "cell": {
    "side": "right",
    "slotRow": 1
   },
   "from": "H1",
   "to": "H1",
   "cells": [
    {
     "reel": 0,
     "row": 1
    },
    {
     "reel": 2,
     "row": 1
    }
   ],
   "totalWays": 13824
  },
  {
   "index": 7,
   "type": "splitSymbols",
   "label": "Split",
   "cell": {
    "side": "right",
    "slotRow": 0
   },
   "symbol": "L2",
   "mult": 9,
   "cells": [
    {
     "reel": 0,
     "row": 2,
     "multiplier": 9
    }
   ],
   "totalWays": 41472
  },
  {
   "index": 8,
   "type": "cloneSymbol",
   "label": "Clone",
   "cell": {
    "side": "left",
    "slotRow": 0
   },
   "from": "H3",
   "to": "H4",
   "cells": [
    {
     "reel": 1,
     "row": 1
    },
    {
     "reel": 1,
     "row": 2
    },
    {
     "reel": 3,
     "row": 2
    }
   ],
   "totalWays": 32256
  },
  {
   "index": 9,
   "type": "cloneSymbol",
   "label": "Clone",
   "cell": {
    "side": "left",
    "slotRow": 1
   },
   "from": "H5",
   "to": "H5",
   "cells": [
    {
     "reel": 1,
     "row": 3
    }
   ],
   "totalWays": 32256
  },
  {
   "index": 10,
   "type": "splitSymbols",
   "label": "Split",
   "cell": {
    "side": "left",
    "slotRow": 2
   },
   "symbol": "L5",
   "mult": 9,
   "cells": [
    {
     "reel": 0,
     "row": 3,
     "multiplier": 9
    }
   ],
   "totalWays": 53760
  },
  {
   "index": 11,
   "type": "winInfo",
   "totalWin": 8580,
   "wins": [
    {
     "symbol": "H1",
     "kind": 3,
     "win": 2100,
     "positions": [
      {
       "reel": 0,
       "row": 1
      },
      {
       "reel": 1,
       "row": 4
      },
      {
       "reel": 2,
       "row": 1
      },
      {
       "reel": 2,
       "row": 3
      },
      {
       "reel": 2,
       "row": 4
      }
     ],
     "meta": {
      "ways": 21,
      "globalMult": 1,
      "winWithoutMult": 2100,
      "symbolMult": 8
     }
    },
    {
     "symbol": "L2",
     "kind": 3,
     "win": 3240,
     "positions": [
      {
       "reel": 0,
       "row": 2
      },
      {
       "reel": 1,
       "row": 4
      },
      {
       "reel": 2,
       "row": 3
      },
      {
       "reel": 2,
       "row": 4
      }
     ],
     "meta": {
      "ways": 162,
      "globalMult": 1,
      "winWithoutMult": 3240,
      "symbolMult": 8
     }
    },
    {
     "symbol": "L3",
     "kind": 4,
     "win": 1620,
     "positions": [
      {
       "reel": 0,
       "row": 4
      },
      {
       "reel": 1,
       "row": 4
      },
      {
       "reel": 2,
       "row": 3
      },
      {
       "reel": 2,
       "row": 4
      },
      {
       "reel": 3,
       "row": 1
      }
     ],
     "meta": {
      "ways": 54,
      "globalMult": 1,
      "winWithoutMult": 1620,
      "symbolMult": 8
     }
    },
    {
     "symbol": "L5",
     "kind": 3,
     "win": 1620,
     "positions": [
      {
       "reel": 0,
       "row": 3
      },
      {
       "reel": 1,
       "row": 4
      },
      {
       "reel": 2,
       "row": 3
      },
      {
       "reel": 2,
       "row": 4
      }
     ],
     "meta": {
      "ways": 162,
      "globalMult": 1,
      "winWithoutMult": 1620,
      "symbolMult": 8
     }
    }
   ]
  },
  {
   "index": 12,
   "type": "setWin",
   "amount": 8580,
   "winLevel": 8
  },
  {
   "type": "setTotalWin",
   "amount": 8580,
   "index": 13
  },
  {
   "type": "finalWin",
   "amount": 8580,
   "index": 14
  }
 ]
} as ShowcaseBook;

export default allFeaturesBook;
