// GENERATED by math-sdk/games/0_2_the_white_room/make_all_features_book.py
// ONE bonus spin where every feature fires: Unlocked Slots + Wild Reel +
// Stretch + Clone + Split, resolving into a win. Plays through the live Game.
import type { BookEvent } from '../../game/typesBookEvent';

type ShowcaseBook = { id: number; payoutMultiplier: number; events: BookEvent[] };

export const allFeaturesBook: ShowcaseBook =
	{
 "id": 1828,
 "payoutMultiplier": 41580,
 "events": [
  {
   "type": "bonusLevel",
   "level": 3,
   "name": "ALL FEATURES",
   "startHaunted": [],
   "index": 0
  },
  {
   "index": 1,
   "type": "reveal",
   "board": [
    [
     {
      "name": "H1"
     },
     {
      "name": "H5"
     },
     {
      "name": "L2"
     },
     {
      "name": "L5"
     },
     {
      "name": "L3"
     },
     {
      "name": "H2"
     }
    ],
    [
     {
      "name": "L5"
     },
     {
      "name": "H5"
     },
     {
      "name": "L4"
     },
     {
      "name": "L3"
     },
     {
      "name": "H3"
     }
    ],
    [
     {
      "name": "L5"
     },
     {
      "name": "L5"
     },
     {
      "name": "L4"
     },
     {
      "name": "L2"
     }
    ],
    [
     {
      "name": "L2"
     },
     {
      "name": "H4"
     },
     {
      "name": "L4"
     },
     {
      "name": "H3"
     },
     {
      "name": "H2"
     }
    ],
    [
     {
      "name": "S",
      "scatter": true
     },
     {
      "name": "L1"
     },
     {
      "name": "L1"
     },
     {
      "name": "H1"
     },
     {
      "name": "L1"
     },
     {
      "name": "H1"
     }
    ]
   ],
   "paddingPositions": [
    92,
    230,
    98,
    244,
    139
   ],
   "gameType": "freegame",
   "anticipation": [
    0,
    0,
    0,
    0,
    0
   ]
  },
  {
   "index": 2,
   "type": "unlockedSlots",
   "label": "Unlocked Slots",
   "level": 3,
   "unlocked": [
    "bottom",
    "right",
    "left"
   ],
   "bottom": [],
   "sides": [
    {
     "side": "left",
     "reel": 5,
     "cells": [
      {
       "row": 1,
       "slotRow": 0,
       "name": "W",
       "multiplier": 10
      },
      {
       "row": 2,
       "slotRow": 1,
       "name": "W",
       "multiplier": 2
      }
     ]
    }
   ],
   "totalWays": 3456
  },
  {
   "index": 3,
   "type": "wildReel",
   "label": "Wild Reel",
   "reels": [
    {
     "reel": 1,
     "baseRows": 3,
     "added": 1,
     "cells": [
      {
       "row": 4,
       "multiplier": 2
      }
     ],
     "ways": 5
    }
   ],
   "totalWays": 5760
  },
  {
   "index": 4,
   "type": "stretchReel",
   "label": "Stretch",
   "reels": [
    {
     "reel": 2,
     "mode": "normal",
     "baseRows": 2,
     "reelWays": 18,
     "cells": [
      {
       "row": 1,
       "multiplier": 8
      },
      {
       "row": 2,
       "multiplier": 10
      }
     ]
    }
   ],
   "totalWays": 51840
  },
  {
   "index": 5,
   "type": "stretchReel",
   "label": "Stretch",
   "reels": [
    {
     "reel": 3,
     "mode": "normal",
     "baseRows": 3,
     "reelWays": 22,
     "cells": [
      {
       "row": 1,
       "multiplier": 10
      },
      {
       "row": 2,
       "multiplier": 6
      },
      {
       "row": 3,
       "multiplier": 6
      }
     ]
    }
   ],
   "totalWays": 380160
  },
  {
   "index": 6,
   "type": "splitSymbols",
   "label": "Split",
   "cell": {
    "side": "right",
    "slotRow": 2
   },
   "symbol": "L5",
   "mult": 10,
   "cells": [
    {
     "reel": 0,
     "row": 3,
     "multiplier": 11
    },
    {
     "reel": 2,
     "row": 1,
     "multiplier": 18
    },
    {
     "reel": 1,
     "row": 4,
     "multiplier": 12,
     "wild": true
    }
   ],
   "wildReels": [
    {
     "reel": 1,
     "ways": 15
    }
   ],
   "totalWays": 6209280
  },
  {
   "index": 7,
   "type": "cloneSymbol",
   "label": "Clone",
   "cell": {
    "side": "right",
    "slotRow": 1
   },
   "from": "L4",
   "to": "H3",
   "cells": [
    {
     "reel": 2,
     "row": 2
    },
    {
     "reel": 3,
     "row": 2
    }
   ],
   "totalWays": 6209280
  },
  {
   "index": 8,
   "type": "cloneSymbol",
   "label": "Clone",
   "cell": {
    "side": "right",
    "slotRow": 0
   },
   "from": "H1",
   "to": "H5",
   "cells": [
    {
     "reel": 4,
     "row": 3
    }
   ],
   "totalWays": 6209280
  },
  {
   "index": 9,
   "type": "splitSymbols",
   "label": "Split",
   "cell": {
    "side": "left",
    "slotRow": 2
   },
   "symbol": "W",
   "mult": 9,
   "cells": [
    {
     "reel": 1,
     "row": 4,
     "multiplier": 21,
     "wild": true
    }
   ],
   "wildReels": [
    {
     "reel": 1,
     "ways": 24
    }
   ],
   "totalWays": 9934848
  },
  {
   "index": 10,
   "type": "winInfo",
   "totalWin": 41580,
   "wins": [
    {
     "symbol": "L5",
     "kind": 3,
     "win": 41580,
     "positions": [
      {
       "reel": 0,
       "row": 3
      },
      {
       "reel": 1,
       "row": 4
      },
      {
       "reel": 2,
       "row": 1
      }
     ],
     "meta": {
      "ways": 4158,
      "globalMult": 1,
      "winWithoutMult": 41580,
      "symbolMult": 21
     }
    }
   ]
  },
  {
   "index": 11,
   "type": "setWin",
   "amount": 41580,
   "winLevel": 9
  },
  {
   "type": "setTotalWin",
   "amount": 41580,
   "index": 12
  },
  {
   "type": "finalWin",
   "amount": 41580,
   "index": 13
  }
 ]
} as ShowcaseBook;

export default allFeaturesBook;
