// GENERATED by math-sdk/games/0_2_the_white_room/make_combo_book.py
// ONE NATURAL bonus spin picked for the richest feature mix: clones + splits
// (across bottom AND side cells) + wild reel(s) + normal & wild stretch,
// resolving into a real win. Plays through the live Game.
import type { BookEvent } from '../../game/typesBookEvent';

type ShowcaseBook = { id: number; payoutMultiplier: number; events: BookEvent[] };

export const comboFeaturesBook: ShowcaseBook =
	{
 "id": 5815,
 "payoutMultiplier": 39900,
 "events": [
  {
   "type": "bonusLevel",
   "level": 3,
   "name": "FEATURE STORM",
   "startHaunted": [],
   "index": 0
  },
  {
   "index": 1,
   "type": "reveal",
   "board": [
    [
     {
      "name": "L5"
     },
     {
      "name": "L4"
     },
     {
      "name": "L2"
     },
     {
      "name": "H1"
     },
     {
      "name": "H3"
     },
     {
      "name": "H3"
     }
    ],
    [
     {
      "name": "L5"
     },
     {
      "name": "H2"
     },
     {
      "name": "H5"
     },
     {
      "name": "H2"
     },
     {
      "name": "H1"
     }
    ],
    [
     {
      "name": "H4"
     },
     {
      "name": "H3"
     },
     {
      "name": "L4"
     },
     {
      "name": "L2"
     }
    ],
    [
     {
      "name": "L4"
     },
     {
      "name": "L1"
     },
     {
      "name": "H4"
     },
     {
      "name": "L1"
     },
     {
      "name": "L2"
     }
    ],
    [
     {
      "name": "L2"
     },
     {
      "name": "L5"
     },
     {
      "name": "L2"
     },
     {
      "name": "L4"
     },
     {
      "name": "H3"
     },
     {
      "name": "L2"
     }
    ]
   ],
   "paddingPositions": [
    161,
    192,
    177,
    32,
    77
   ],
   "gameType": "freegame",
   "anticipation": [
    0,
    0,
    0,
    0,
    0
   ]
  },
  {
   "index": 2,
   "type": "unlockedSlots",
   "label": "Unlocked Slots",
   "level": 3,
   "unlocked": [
    "bottom",
    "right",
    "left"
   ],
   "bottom": [],
   "sides": [],
   "totalWays": 288
  },
  {
   "index": 3,
   "type": "stretchReel",
   "label": "Stretch",
   "reels": [
    {
     "reel": 1,
     "mode": "normal",
     "baseRows": 3,
     "reelWays": 7,
     "cells": [
      {
       "row": 1,
       "multiplier": 2
      },
      {
       "row": 2,
       "multiplier": 3
      },
      {
       "row": 3,
       "multiplier": 2
      }
     ]
    }
   ],
   "totalWays": 672
  },
  {
   "index": 4,
   "type": "wildReel",
   "label": "Wild Reel",
   "reels": [
    {
     "reel": 2,
     "baseRows": 2,
     "added": 2,
     "cells": [
      {
       "row": 3,
       "multiplier": 1
      },
      {
       "row": 4,
       "multiplier": 1
      }
     ],
     "ways": 4
    }
   ],
   "totalWays": 1344
  },
  {
   "index": 5,
   "type": "splitSymbols",
   "label": "Split",
   "cell": {
    "reel": 3
   },
   "symbol": "W",
   "mult": 3,
   "cells": [
    {
     "reel": 2,
     "row": 3,
     "multiplier": 4,
     "wild": true
    },
    {
     "reel": 2,
     "row": 4,
     "multiplier": 4,
     "wild": true
    }
   ],
   "wildReels": [
    {
     "reel": 2,
     "ways": 10
    }
   ],
   "totalWays": 3360
  },
  {
   "index": 6,
   "type": "splitSymbols",
   "label": "Split",
   "cell": {
    "side": "right",
    "slotRow": 2
   },
   "symbol": "W",
   "mult": 2,
   "cells": [
    {
     "reel": 2,
     "row": 3,
     "multiplier": 6,
     "wild": true
    },
    {
     "reel": 2,
     "row": 4,
     "multiplier": 6,
     "wild": true
    }
   ],
   "wildReels": [
    {
     "reel": 2,
     "ways": 14
    }
   ],
   "totalWays": 4704
  },
  {
   "index": 7,
   "type": "splitSymbols",
   "label": "Split",
   "cell": {
    "side": "right",
    "slotRow": 1
   },
   "symbol": "W",
   "mult": 1,
   "cells": [
    {
     "reel": 2,
     "row": 3,
     "multiplier": 7,
     "wild": true
    },
    {
     "reel": 2,
     "row": 4,
     "multiplier": 7,
     "wild": true
    }
   ],
   "wildReels": [
    {
     "reel": 2,
     "ways": 16
    }
   ],
   "totalWays": 5376
  },
  {
   "index": 8,
   "type": "cloneSymbol",
   "label": "Clone",
   "cell": {
    "side": "right",
    "slotRow": 0
   },
   "from": "H1",
   "to": "H5",
   "cells": [
    {
     "reel": 0,
     "row": 3
    }
   ],
   "totalWays": 5376
  },
  {
   "index": 9,
   "type": "cloneSymbol",
   "label": "Clone",
   "cell": {
    "side": "left",
    "slotRow": 0
   },
   "from": "H2",
   "to": "H3",
   "cells": [
    {
     "reel": 1,
     "row": 1
    },
    {
     "reel": 1,
     "row": 3
    }
   ],
   "totalWays": 5376
  },
  {
   "index": 10,
   "type": "splitSymbols",
   "label": "Split",
   "cell": {
    "side": "left",
    "slotRow": 1
   },
   "symbol": "H3",
   "mult": 2,
   "cells": [
    {
     "reel": 0,
     "row": 4,
     "multiplier": 3
    },
    {
     "reel": 1,
     "row": 1,
     "multiplier": 4
    },
    {
     "reel": 1,
     "row": 3,
     "multiplier": 4
    },
    {
     "reel": 2,
     "row": 1,
     "multiplier": 3
    },
    {
     "reel": 2,
     "row": 3,
     "multiplier": 9,
     "wild": true
    },
    {
     "reel": 2,
     "row": 4,
     "multiplier": 9,
     "wild": true
    }
   ],
   "wildReels": [
    {
     "reel": 2,
     "ways": 22
    }
   ],
   "totalWays": 17424
  },
  {
   "index": 11,
   "type": "splitSymbols",
   "label": "Split",
   "cell": {
    "side": "left",
    "slotRow": 2
   },
   "symbol": "H5",
   "mult": 2,
   "cells": [
    {
     "reel": 0,
     "row": 3,
     "multiplier": 3
    },
    {
     "reel": 1,
     "row": 2,
     "multiplier": 5
    },
    {
     "reel": 2,
     "row": 3,
     "multiplier": 11,
     "wild": true
    },
    {
     "reel": 2,
     "row": 4,
     "multiplier": 11,
     "wild": true
    }
   ],
   "wildReels": [
    {
     "reel": 2,
     "ways": 26
    }
   ],
   "totalWays": 32448
  },
  {
   "index": 12,
   "type": "winInfo",
   "totalWin": 39900,
   "wins": [
    {
     "symbol": "H3",
     "kind": 3,
     "win": 30000,
     "positions": [
      {
       "reel": 0,
       "row": 4
      },
      {
       "reel": 1,
       "row": 1
      },
      {
       "reel": 1,
       "row": 3
      },
      {
       "reel": 2,
       "row": 1
      },
      {
       "reel": 2,
       "row": 3
      },
      {
       "reel": 2,
       "row": 4
      }
     ],
     "meta": {
      "ways": 600,
      "globalMult": 1,
      "winWithoutMult": 30000,
      "symbolMult": 22
     }
    },
    {
     "symbol": "H5",
     "kind": 3,
     "win": 9900,
     "positions": [
      {
       "reel": 0,
       "row": 3
      },
      {
       "reel": 1,
       "row": 2
      },
      {
       "reel": 2,
       "row": 3
      },
      {
       "reel": 2,
       "row": 4
      }
     ],
     "meta": {
      "ways": 330,
      "globalMult": 1,
      "winWithoutMult": 9900,
      "symbolMult": 22
     }
    }
   ]
  },
  {
   "index": 13,
   "type": "setWin",
   "amount": 39900,
   "winLevel": 9
  },
  {
   "type": "setTotalWin",
   "amount": 39900,
   "index": 14
  },
  {
   "type": "finalWin",
   "amount": 39900,
   "index": 15
  }
 ]
} as ShowcaseBook;

export default comboFeaturesBook;
