// GENERATED by math-sdk/games/0_2_the_white_room/make_combo_book.py
// ONE NATURAL bonus spin picked for the richest feature mix: clones + splits
// (across bottom AND side cells) + wild reel(s) + normal & wild stretch,
// resolving into a real win. Plays through the live Game.
import type { BookEvent } from '../../game/typesBookEvent';

type ShowcaseBook = { id: number; payoutMultiplier: number; events: BookEvent[] };

export const comboFeaturesBook: ShowcaseBook =
	{
 "id": 416,
 "payoutMultiplier": 18560,
 "events": [
  {
   "type": "bonusLevel",
   "level": 3,
   "name": "FEATURE STORM",
   "startHaunted": [],
   "index": 0
  },
  {
   "index": 1,
   "type": "reveal",
   "board": [
    [
     {
      "name": "L2"
     },
     {
      "name": "H1"
     },
     {
      "name": "L5"
     },
     {
      "name": "L3"
     },
     {
      "name": "L4"
     },
     {
      "name": "L4"
     }
    ],
    [
     {
      "name": "L5"
     },
     {
      "name": "L2"
     },
     {
      "name": "L4"
     },
     {
      "name": "L3"
     },
     {
      "name": "L2"
     }
    ],
    [
     {
      "name": "H1"
     },
     {
      "name": "L4"
     },
     {
      "name": "L5"
     },
     {
      "name": "L4"
     }
    ],
    [
     {
      "name": "H1"
     },
     {
      "name": "L4"
     },
     {
      "name": "L4"
     },
     {
      "name": "H2"
     },
     {
      "name": "W",
      "wild": true
     }
    ],
    [
     {
      "name": "H4"
     },
     {
      "name": "L2"
     },
     {
      "name": "H4"
     },
     {
      "name": "H2"
     },
     {
      "name": "L5"
     },
     {
      "name": "L3"
     }
    ]
   ],
   "paddingPositions": [
    212,
    153,
    7,
    231,
    208
   ],
   "gameType": "freegame",
   "anticipation": [
    0,
    0,
    0,
    0,
    0
   ]
  },
  {
   "index": 2,
   "type": "unlockedSlots",
   "label": "Unlocked Slots",
   "level": 3,
   "unlocked": [
    "bottom",
    "right",
    "left"
   ],
   "bottom": [],
   "sides": [],
   "totalWays": 288
  },
  {
   "index": 3,
   "type": "stretchReel",
   "label": "Stretch",
   "reels": [
    {
     "reel": 1,
     "mode": "normal",
     "baseRows": 3,
     "reelWays": 5,
     "cells": [
      {
       "row": 1,
       "multiplier": 3
      },
      {
       "row": 2,
       "multiplier": 1
      },
      {
       "row": 3,
       "multiplier": 1
      }
     ]
    }
   ],
   "totalWays": 480
  },
  {
   "index": 4,
   "type": "wildReel",
   "label": "Wild Reel",
   "reels": [
    {
     "reel": 2,
     "baseRows": 2,
     "added": 2,
     "cells": [
      {
       "row": 3,
       "multiplier": 1
      },
      {
       "row": 4,
       "multiplier": 1
      }
     ]
    }
   ],
   "totalWays": 960
  },
  {
   "index": 5,
   "type": "stretchReel",
   "label": "Stretch",
   "reels": [
    {
     "reel": 3,
     "mode": "wild",
     "baseRows": 3,
     "reelWays": 4,
     "cells": [
      {
       "row": 1,
       "multiplier": 2
      },
      {
       "row": 2,
       "multiplier": 1
      },
      {
       "row": 3,
       "multiplier": 1
      }
     ]
    }
   ],
   "totalWays": 1280
  },
  {
   "index": 6,
   "type": "splitSymbols",
   "label": "Split",
   "cell": {
    "side": "right",
    "slotRow": 2
   },
   "symbol": "L3",
   "mult": 2,
   "cells": [
    {
     "reel": 0,
     "row": 3,
     "multiplier": 2
    },
    {
     "reel": 1,
     "row": 3,
     "multiplier": 2
    }
   ],
   "totalWays": 1920
  },
  {
   "index": 7,
   "type": "cloneSymbol",
   "label": "Clone",
   "cell": {
    "side": "right",
    "slotRow": 1
   },
   "from": "L2",
   "to": "H4",
   "cells": [
    {
     "reel": 1,
     "row": 1
    },
    {
     "reel": 4,
     "row": 1
    }
   ],
   "totalWays": 1280
  },
  {
   "index": 8,
   "type": "cloneSymbol",
   "label": "Clone",
   "cell": {
    "side": "right",
    "slotRow": 0
   },
   "from": "H4",
   "to": "H1",
   "cells": [
    {
     "reel": 1,
     "row": 1
    },
    {
     "reel": 4,
     "row": 1
    },
    {
     "reel": 4,
     "row": 2
    }
   ],
   "totalWays": 1280
  },
  {
   "index": 9,
   "type": "splitSymbols",
   "label": "Split",
   "cell": {
    "side": "left",
    "slotRow": 0
   },
   "symbol": "L4",
   "mult": 2,
   "cells": [
    {
     "reel": 0,
     "row": 4,
     "multiplier": 2
    },
    {
     "reel": 1,
     "row": 2,
     "multiplier": 2
    },
    {
     "reel": 2,
     "row": 1,
     "multiplier": 2
    }
   ],
   "totalWays": 2400
  },
  {
   "index": 10,
   "type": "cloneSymbol",
   "label": "Clone",
   "cell": {
    "side": "left",
    "slotRow": 1
   },
   "from": "L3",
   "to": "H5",
   "cells": [
    {
     "reel": 0,
     "row": 3
    },
    {
     "reel": 1,
     "row": 3
    }
   ],
   "totalWays": 1600
  },
  {
   "index": 11,
   "type": "cloneSymbol",
   "label": "Clone",
   "cell": {
    "side": "left",
    "slotRow": 2
   },
   "from": "H5",
   "to": "H5",
   "cells": [
    {
     "reel": 0,
     "row": 3
    },
    {
     "reel": 1,
     "row": 3
    }
   ],
   "totalWays": 1600
  },
  {
   "index": 12,
   "type": "winInfo",
   "totalWin": 18560,
   "wins": [
    {
     "symbol": "H1",
     "kind": 5,
     "win": 16000,
     "positions": [
      {
       "reel": 0,
       "row": 1
      },
      {
       "reel": 1,
       "row": 1
      },
      {
       "reel": 2,
       "row": 3
      },
      {
       "reel": 2,
       "row": 4
      },
      {
       "reel": 3,
       "row": 1
      },
      {
       "reel": 3,
       "row": 2
      },
      {
       "reel": 3,
       "row": 3
      },
      {
       "reel": 4,
       "row": 1
      },
      {
       "reel": 4,
       "row": 2
      }
     ],
     "meta": {
      "ways": 16,
      "globalMult": 1,
      "winWithoutMult": 16000,
      "symbolMult": 2
     }
    },
    {
     "symbol": "H5",
     "kind": 4,
     "win": 640,
     "positions": [
      {
       "reel": 0,
       "row": 3
      },
      {
       "reel": 1,
       "row": 3
      },
      {
       "reel": 2,
       "row": 3
      },
      {
       "reel": 2,
       "row": 4
      },
      {
       "reel": 3,
       "row": 1
      },
      {
       "reel": 3,
       "row": 2
      },
      {
       "reel": 3,
       "row": 3
      }
     ],
     "meta": {
      "ways": 8,
      "globalMult": 1,
      "winWithoutMult": 640,
      "symbolMult": 2
     }
    },
    {
     "symbol": "L4",
     "kind": 4,
     "win": 1920,
     "positions": [
      {
       "reel": 0,
       "row": 4
      },
      {
       "reel": 1,
       "row": 2
      },
      {
       "reel": 2,
       "row": 1
      },
      {
       "reel": 2,
       "row": 3
      },
      {
       "reel": 2,
       "row": 4
      },
      {
       "reel": 3,
       "row": 1
      },
      {
       "reel": 3,
       "row": 2
      },
      {
       "reel": 3,
       "row": 3
      }
     ],
     "meta": {
      "ways": 64,
      "globalMult": 1,
      "winWithoutMult": 1920,
      "symbolMult": 2
     }
    }
   ]
  },
  {
   "index": 13,
   "type": "setWin",
   "amount": 18560,
   "winLevel": 9
  },
  {
   "type": "setTotalWin",
   "amount": 18560,
   "index": 14
  },
  {
   "type": "finalWin",
   "amount": 18560,
   "index": 15
  }
 ]
} as ShowcaseBook;

export default comboFeaturesBook;
