// GENERATED by math-sdk/games/0_2_the_white_room/make_slot_books.py
// Real UNLOCKED SLOTS books pulled from the build - each plays through
// the live Game so the slot-drop + 6/7-wide resolution is exact.
import type { BookEvent } from '../../game/typesBookEvent';

type ShowcaseBook = { id: number; payoutMultiplier: number; events: BookEvent[] };

export const unlockedSlotsLevel1Book: ShowcaseBook =
	{
 "id": 87,
 "payoutMultiplier": 15000,
 "events": [
  {
   "index": 0,
   "type": "reveal",
   "board": [
    [
     {
      "name": "H4"
     },
     {
      "name": "H5"
     },
     {
      "name": "H1"
     },
     {
      "name": "H3"
     },
     {
      "name": "H3"
     },
     {
      "name": "H4"
     }
    ],
    [
     {
      "name": "H2"
     },
     {
      "name": "H5"
     },
     {
      "name": "L5"
     },
     {
      "name": "H5"
     },
     {
      "name": "L2"
     }
    ],
    [
     {
      "name": "W",
      "wild": true
     },
     {
      "name": "L3"
     },
     {
      "name": "H4"
     },
     {
      "name": "H3"
     }
    ],
    [
     {
      "name": "L4"
     },
     {
      "name": "H3"
     },
     {
      "name": "S",
      "scatter": true
     },
     {
      "name": "H4"
     },
     {
      "name": "L5"
     }
    ],
    [
     {
      "name": "L2"
     },
     {
      "name": "L4"
     },
     {
      "name": "H3"
     },
     {
      "name": "L2"
     },
     {
      "name": "L4"
     },
     {
      "name": "H2"
     }
    ]
   ],
   "paddingPositions": [
    155,
    99,
    40,
    88,
    79
   ],
   "gameType": "basegame",
   "anticipation": [
    0,
    0,
    0,
    0,
    1
   ]
  },
  {
   "index": 1,
   "type": "unlockedSlots",
   "label": "Unlocked Slots",
   "level": 1,
   "unlocked": [
    "bottom"
   ],
   "bottom": [],
   "sides": [],
   "totalWays": 288
  },
  {
   "index": 2,
   "type": "wildReel",
   "label": "Wild Reel",
   "reels": [
    {
     "reel": 1,
     "baseRows": 3,
     "added": 1,
     "cells": [
      {
       "row": 4,
       "multiplier": 1
      }
     ],
     "ways": 4
    }
   ],
   "totalWays": 384
  },
  {
   "index": 3,
   "type": "wildReel",
   "label": "Wild Reel",
   "reels": [
    {
     "reel": 2,
     "baseRows": 2,
     "added": 2,
     "cells": [
      {
       "row": 3,
       "multiplier": 1
      },
      {
       "row": 4,
       "multiplier": 1
      }
     ],
     "ways": 4
    }
   ],
   "totalWays": 768
  },
  {
   "index": 4,
   "type": "wildReel",
   "label": "Wild Reel",
   "reels": [
    {
     "reel": 3,
     "baseRows": 3,
     "added": 1,
     "cells": [
      {
       "row": 4,
       "multiplier": 5
      }
     ],
     "ways": 8
    }
   ],
   "totalWays": 2048
  },
  {
   "index": 5,
   "type": "winInfo",
   "totalWin": 15000,
   "wins": [
    {
     "symbol": "H1",
     "kind": 4,
     "win": 3000,
     "positions": [
      {
       "reel": 0,
       "row": 2
      },
      {
       "reel": 1,
       "row": 4
      },
      {
       "reel": 2,
       "row": 3
      },
      {
       "reel": 2,
       "row": 4
      },
      {
       "reel": 3,
       "row": 4
      }
     ],
     "meta": {
      "ways": 10,
      "globalMult": 1,
      "winWithoutMult": 3000,
      "symbolMult": 5
     }
    },
    {
     "symbol": "H3",
     "kind": 5,
     "win": 9600,
     "positions": [
      {
       "reel": 0,
       "row": 3
      },
      {
       "reel": 0,
       "row": 4
      },
      {
       "reel": 1,
       "row": 4
      },
      {
       "reel": 2,
       "row": 3
      },
      {
       "reel": 2,
       "row": 4
      },
      {
       "reel": 3,
       "row": 1
      },
      {
       "reel": 3,
       "row": 4
      },
      {
       "reel": 4,
       "row": 2
      }
     ],
     "meta": {
      "ways": 24,
      "globalMult": 1,
      "winWithoutMult": 9600,
      "symbolMult": 5
     }
    },
    {
     "symbol": "H5",
     "kind": 4,
     "win": 2400,
     "positions": [
      {
       "reel": 0,
       "row": 1
      },
      {
       "reel": 1,
       "row": 1
      },
      {
       "reel": 1,
       "row": 3
      },
      {
       "reel": 1,
       "row": 4
      },
      {
       "reel": 2,
       "row": 3
      },
      {
       "reel": 2,
       "row": 4
      },
      {
       "reel": 3,
       "row": 4
      }
     ],
     "meta": {
      "ways": 30,
      "globalMult": 1,
      "winWithoutMult": 2400,
      "symbolMult": 5
     }
    }
   ]
  },
  {
   "index": 6,
   "type": "setWin",
   "amount": 15000,
   "winLevel": 9
  },
  {
   "type": "setTotalWin",
   "amount": 15000,
   "index": 7
  },
  {
   "type": "finalWin",
   "amount": 15000,
   "index": 8
  }
 ]
} as ShowcaseBook;

export const unlockedSlotsLevel2Book: ShowcaseBook =
	{
 "id": 357,
 "payoutMultiplier": 15040,
 "events": [
  {
   "index": 0,
   "type": "reveal",
   "board": [
    [
     {
      "name": "L3"
     },
     {
      "name": "H3"
     },
     {
      "name": "L1"
     },
     {
      "name": "H4"
     },
     {
      "name": "H5"
     },
     {
      "name": "L1"
     }
    ],
    [
     {
      "name": "W",
      "wild": true
     },
     {
      "name": "H4"
     },
     {
      "name": "H2"
     },
     {
      "name": "H1"
     },
     {
      "name": "L2"
     }
    ],
    [
     {
      "name": "H1"
     },
     {
      "name": "H5"
     },
     {
      "name": "L4"
     },
     {
      "name": "H2"
     }
    ],
    [
     {
      "name": "H4"
     },
     {
      "name": "L1"
     },
     {
      "name": "L2"
     },
     {
      "name": "W",
      "wild": true
     },
     {
      "name": "L2"
     }
    ],
    [
     {
      "name": "L4"
     },
     {
      "name": "L4"
     },
     {
      "name": "H1"
     },
     {
      "name": "H4"
     },
     {
      "name": "H3"
     },
     {
      "name": "L5"
     }
    ]
   ],
   "paddingPositions": [
    168,
    177,
    196,
    34,
    15
   ],
   "gameType": "basegame",
   "anticipation": [
    0,
    0,
    0,
    0,
    0
   ]
  },
  {
   "index": 1,
   "type": "unlockedSlots",
   "label": "Unlocked Slots",
   "level": 2,
   "unlocked": [
    "bottom",
    "right"
   ],
   "bottom": [
    {
     "reel": 2,
     "row": 3,
     "name": "H4"
    }
   ],
   "sides": [
    {
     "side": "right",
     "reel": 5,
     "cells": [
      {
       "row": 1,
       "slotRow": 0,
       "name": "H4"
      },
      {
       "row": 2,
       "slotRow": 2,
       "name": "W",
       "multiplier": 1
      }
     ]
    }
   ],
   "totalWays": 864
  },
  {
   "index": 2,
   "type": "wildReel",
   "label": "Wild Reel",
   "reels": [
    {
     "reel": 1,
     "baseRows": 3,
     "added": 1,
     "cells": [
      {
       "row": 4,
       "multiplier": 1
      }
     ],
     "ways": 4
    }
   ],
   "totalWays": 1152
  },
  {
   "index": 3,
   "type": "wildReel",
   "label": "Wild Reel",
   "reels": [
    {
     "reel": 3,
     "baseRows": 3,
     "added": 1,
     "cells": [
      {
       "row": 4,
       "multiplier": 3
      }
     ],
     "ways": 6
    }
   ],
   "totalWays": 2304
  },
  {
   "index": 4,
   "type": "cloneSymbol",
   "label": "Clone",
   "cell": {
    "side": "right",
    "slotRow": 1
   },
   "from": "L1",
   "to": "H5",
   "cells": [
    {
     "reel": 0,
     "row": 2
    }
   ],
   "totalWays": 2304
  },
  {
   "index": 5,
   "type": "winInfo",
   "totalWin": 15040,
   "wins": [
    {
     "symbol": "H4",
     "kind": 6,
     "win": 14400,
     "positions": [
      {
       "reel": 0,
       "row": 3
      },
      {
       "reel": 1,
       "row": 1
      },
      {
       "reel": 1,
       "row": 4
      },
      {
       "reel": 2,
       "row": 3
      },
      {
       "reel": 3,
       "row": 3
      },
      {
       "reel": 3,
       "row": 4
      },
      {
       "reel": 4,
       "row": 3
      },
      {
       "reel": 5,
       "row": 1
      },
      {
       "reel": 5,
       "row": 2
      }
     ],
     "meta": {
      "ways": 16,
      "globalMult": 1,
      "winWithoutMult": 14400,
      "symbolMult": 3
     }
    },
    {
     "symbol": "H5",
     "kind": 4,
     "win": 640,
     "positions": [
      {
       "reel": 0,
       "row": 2
      },
      {
       "reel": 0,
       "row": 4
      },
      {
       "reel": 1,
       "row": 4
      },
      {
       "reel": 2,
       "row": 1
      },
      {
       "reel": 3,
       "row": 3
      },
      {
       "reel": 3,
       "row": 4
      }
     ],
     "meta": {
      "ways": 8,
      "globalMult": 1,
      "winWithoutMult": 640,
      "symbolMult": 3
     }
    }
   ]
  },
  {
   "index": 6,
   "type": "setWin",
   "amount": 15040,
   "winLevel": 9
  },
  {
   "type": "setTotalWin",
   "amount": 15040,
   "index": 7
  },
  {
   "type": "finalWin",
   "amount": 15040,
   "index": 8
  }
 ]
} as ShowcaseBook;

export const unlockedSlotsLevel3Book: ShowcaseBook =
	{
 "id": 279,
 "payoutMultiplier": 15000,
 "events": [
  {
   "index": 0,
   "type": "reveal",
   "board": [
    [
     {
      "name": "H5"
     },
     {
      "name": "H3"
     },
     {
      "name": "L2"
     },
     {
      "name": "L3"
     },
     {
      "name": "H5"
     },
     {
      "name": "L3"
     }
    ],
    [
     {
      "name": "L5"
     },
     {
      "name": "H2"
     },
     {
      "name": "H5"
     },
     {
      "name": "H2"
     },
     {
      "name": "H1"
     }
    ],
    [
     {
      "name": "L5"
     },
     {
      "name": "S",
      "scatter": true
     },
     {
      "name": "L3"
     },
     {
      "name": "L1"
     }
    ],
    [
     {
      "name": "L4"
     },
     {
      "name": "H4"
     },
     {
      "name": "L2"
     },
     {
      "name": "W",
      "wild": true
     },
     {
      "name": "H5"
     }
    ],
    [
     {
      "name": "L4"
     },
     {
      "name": "L4"
     },
     {
      "name": "H5"
     },
     {
      "name": "H3"
     },
     {
      "name": "L1"
     },
     {
      "name": "L5"
     }
    ]
   ],
   "paddingPositions": [
    20,
    192,
    201,
    142,
    168
   ],
   "gameType": "basegame",
   "anticipation": [
    0,
    0,
    0,
    1,
    2
   ]
  },
  {
   "index": 1,
   "type": "unlockedSlots",
   "label": "Unlocked Slots",
   "level": 3,
   "unlocked": [
    "bottom",
    "right",
    "left"
   ],
   "bottom": [
    {
     "reel": 1,
     "row": 4,
     "name": "H4"
    },
    {
     "reel": 2,
     "row": 3,
     "name": "H5"
    }
   ],
   "sides": [
    {
     "side": "right",
     "reel": 5,
     "cells": [
      {
       "row": 1,
       "slotRow": 0,
       "name": "H3"
      },
      {
       "row": 2,
       "slotRow": 1,
       "name": "H5"
      },
      {
       "row": 3,
       "slotRow": 2,
       "name": "W",
       "multiplier": 2
      }
     ]
    },
    {
     "side": "left",
     "reel": 6,
     "cells": [
      {
       "row": 1,
       "slotRow": 0,
       "name": "H5"
      },
      {
       "row": 2,
       "slotRow": 1,
       "name": "H4"
      },
      {
       "row": 3,
       "slotRow": 2,
       "name": "H3"
      }
     ]
    }
   ],
   "totalWays": 6912
  },
  {
   "index": 2,
   "type": "wildReel",
   "label": "Wild Reel",
   "reels": [
    {
     "reel": 3,
     "baseRows": 3,
     "added": 1,
     "cells": [
      {
       "row": 4,
       "multiplier": 1
      }
     ],
     "ways": 4
    }
   ],
   "totalWays": 9216
  },
  {
   "index": 3,
   "type": "winInfo",
   "totalWin": 15000,
   "wins": [
    {
     "symbol": "H5",
     "kind": 7,
     "win": 15000,
     "positions": [
      {
       "reel": 0,
       "row": 4
      },
      {
       "reel": 1,
       "row": 2
      },
      {
       "reel": 2,
       "row": 3
      },
      {
       "reel": 3,
       "row": 3
      },
      {
       "reel": 3,
       "row": 4
      },
      {
       "reel": 4,
       "row": 2
      },
      {
       "reel": 5,
       "row": 2
      },
      {
       "reel": 5,
       "row": 3
      },
      {
       "reel": 6,
       "row": 1
      }
     ],
     "meta": {
      "ways": 6,
      "globalMult": 1,
      "winWithoutMult": 15000,
      "symbolMult": 2
     }
    }
   ]
  },
  {
   "index": 4,
   "type": "setWin",
   "amount": 15000,
   "winLevel": 9
  },
  {
   "type": "setTotalWin",
   "amount": 15000,
   "index": 5
  },
  {
   "type": "finalWin",
   "amount": 15000,
   "index": 6
  }
 ]
} as ShowcaseBook;

export default [unlockedSlotsLevel1Book, unlockedSlotsLevel2Book, unlockedSlotsLevel3Book];
