// GENERATED by math-sdk/games/0_2_the_white_room/make_slot_books.py
// Real UNLOCKED SLOTS books pulled from the build - each plays through
// the live Game so the slot-drop + 6/7-wide resolution is exact.
import type { BookEvent } from '../../game/typesBookEvent';

type ShowcaseBook = { id: number; payoutMultiplier: number; events: BookEvent[] };

export const unlockedSlotsLevel1Book: ShowcaseBook =
	{
 "id": 188,
 "payoutMultiplier": 15100,
 "events": [
  {
   "index": 0,
   "type": "reveal",
   "board": [
    [
     {
      "name": "L5"
     },
     {
      "name": "L3"
     },
     {
      "name": "H2"
     },
     {
      "name": "H2"
     },
     {
      "name": "H2"
     },
     {
      "name": "L5"
     }
    ],
    [
     {
      "name": "L3"
     },
     {
      "name": "S",
      "scatter": true
     },
     {
      "name": "L2"
     },
     {
      "name": "H4"
     },
     {
      "name": "L3"
     }
    ],
    [
     {
      "name": "L2"
     },
     {
      "name": "H3"
     },
     {
      "name": "L5"
     },
     {
      "name": "L2"
     }
    ],
    [
     {
      "name": "W",
      "wild": true
     },
     {
      "name": "H5"
     },
     {
      "name": "H1"
     },
     {
      "name": "H1"
     },
     {
      "name": "H5"
     }
    ],
    [
     {
      "name": "H3"
     },
     {
      "name": "H3"
     },
     {
      "name": "H5"
     },
     {
      "name": "L4"
     },
     {
      "name": "H2"
     },
     {
      "name": "L3"
     }
    ]
   ],
   "paddingPositions": [
    95,
    248,
    101,
    145,
    41
   ],
   "gameType": "basegame",
   "anticipation": [
    0,
    0,
    1,
    2,
    3
   ]
  },
  {
   "index": 1,
   "type": "wildReel",
   "label": "Wild Reel",
   "reels": [
    {
     "reel": 1,
     "baseRows": 3,
     "added": 1,
     "cells": [
      {
       "row": 4,
       "multiplier": 2
      }
     ]
    },
    {
     "reel": 2,
     "baseRows": 2,
     "added": 2,
     "cells": [
      {
       "row": 3,
       "multiplier": 3
      },
      {
       "row": 4,
       "multiplier": 2
      }
     ]
    }
   ],
   "totalWays": 1680
  },
  {
   "index": 2,
   "type": "unlockedSlots",
   "label": "Unlocked Slots",
   "level": 1,
   "unlocked": [
    "bottom"
   ],
   "bottom": [
    {
     "reel": 3,
     "row": 4,
     "name": "H2"
    }
   ],
   "sides": [],
   "totalWays": 2240
  },
  {
   "index": 3,
   "type": "winInfo",
   "totalWin": 15100,
   "wins": [
    {
     "symbol": "H2",
     "kind": 5,
     "win": 15000,
     "positions": [
      {
       "reel": 0,
       "row": 2
      },
      {
       "reel": 0,
       "row": 3
      },
      {
       "reel": 0,
       "row": 4
      },
      {
       "reel": 1,
       "row": 4
      },
      {
       "reel": 2,
       "row": 3
      },
      {
       "reel": 2,
       "row": 4
      },
      {
       "reel": 3,
       "row": 4
      },
      {
       "reel": 4,
       "row": 4
      }
     ],
     "meta": {
      "ways": 30,
      "globalMult": 1,
      "winWithoutMult": 15000,
      "symbolMult": 7
     }
    },
    {
     "symbol": "L3",
     "kind": 3,
     "win": 100,
     "positions": [
      {
       "reel": 0,
       "row": 1
      },
      {
       "reel": 1,
       "row": 4
      },
      {
       "reel": 2,
       "row": 3
      },
      {
       "reel": 2,
       "row": 4
      }
     ],
     "meta": {
      "ways": 10,
      "globalMult": 1,
      "winWithoutMult": 100,
      "symbolMult": 7
     }
    }
   ]
  },
  {
   "index": 4,
   "type": "setWin",
   "amount": 15100,
   "winLevel": 9
  },
  {
   "type": "setTotalWin",
   "amount": 15100,
   "index": 5
  },
  {
   "type": "finalWin",
   "amount": 15100,
   "index": 6
  }
 ]
} as ShowcaseBook;

export const unlockedSlotsLevel2Book: ShowcaseBook =
	{
 "id": 167,
 "payoutMultiplier": 15000,
 "events": [
  {
   "index": 0,
   "type": "reveal",
   "board": [
    [
     {
      "name": "L4"
     },
     {
      "name": "L5"
     },
     {
      "name": "H4"
     },
     {
      "name": "L2"
     },
     {
      "name": "L3"
     },
     {
      "name": "H3"
     }
    ],
    [
     {
      "name": "L1"
     },
     {
      "name": "L5"
     },
     {
      "name": "L1"
     },
     {
      "name": "L4"
     },
     {
      "name": "L2"
     }
    ],
    [
     {
      "name": "H4"
     },
     {
      "name": "H5"
     },
     {
      "name": "H3"
     },
     {
      "name": "L4"
     }
    ],
    [
     {
      "name": "L4"
     },
     {
      "name": "L1"
     },
     {
      "name": "H4"
     },
     {
      "name": "L1"
     },
     {
      "name": "L2"
     }
    ],
    [
     {
      "name": "L2"
     },
     {
      "name": "L3"
     },
     {
      "name": "L5"
     },
     {
      "name": "L2"
     },
     {
      "name": "L2"
     },
     {
      "name": "L1"
     }
    ]
   ],
   "paddingPositions": [
    64,
    20,
    59,
    32,
    67
   ],
   "gameType": "basegame",
   "anticipation": [
    0,
    0,
    0,
    0,
    0
   ]
  },
  {
   "index": 1,
   "type": "wildReel",
   "label": "Wild Reel",
   "reels": [
    {
     "reel": 1,
     "baseRows": 3,
     "added": 1,
     "cells": [
      {
       "row": 4,
       "multiplier": 2
      }
     ]
    },
    {
     "reel": 2,
     "baseRows": 2,
     "added": 2,
     "cells": [
      {
       "row": 3,
       "multiplier": 2
      },
      {
       "row": 4,
       "multiplier": 1
      }
     ]
    },
    {
     "reel": 3,
     "baseRows": 3,
     "added": 1,
     "cells": [
      {
       "row": 4,
       "multiplier": 2
      }
     ]
    }
   ],
   "totalWays": 2000
  },
  {
   "index": 2,
   "type": "unlockedSlots",
   "label": "Unlocked Slots",
   "level": 2,
   "unlocked": [
    "bottom",
    "right"
   ],
   "bottom": [],
   "sides": [
    {
     "side": "right",
     "reel": 5,
     "cells": [
      {
       "row": 1,
       "slotRow": 1,
       "name": "W",
       "multiplier": 1
      },
      {
       "row": 2,
       "slotRow": 2,
       "name": "H5"
      }
     ]
    }
   ],
   "totalWays": 4000
  },
  {
   "index": 3,
   "type": "winInfo",
   "totalWin": 15000,
   "wins": [
    {
     "symbol": "H4",
     "kind": 4,
     "win": 1800,
     "positions": [
      {
       "reel": 0,
       "row": 2
      },
      {
       "reel": 1,
       "row": 4
      },
      {
       "reel": 2,
       "row": 3
      },
      {
       "reel": 2,
       "row": 4
      },
      {
       "reel": 3,
       "row": 2
      },
      {
       "reel": 3,
       "row": 4
      }
     ],
     "meta": {
      "ways": 18,
      "globalMult": 1,
      "winWithoutMult": 1800,
      "symbolMult": 6
     }
    },
    {
     "symbol": "L2",
     "kind": 6,
     "win": 7200,
     "positions": [
      {
       "reel": 0,
       "row": 3
      },
      {
       "reel": 1,
       "row": 4
      },
      {
       "reel": 2,
       "row": 3
      },
      {
       "reel": 2,
       "row": 4
      },
      {
       "reel": 3,
       "row": 4
      },
      {
       "reel": 4,
       "row": 3
      },
      {
       "reel": 4,
       "row": 4
      },
      {
       "reel": 5,
       "row": 1
      }
     ],
     "meta": {
      "ways": 24,
      "globalMult": 1,
      "winWithoutMult": 7200,
      "symbolMult": 6
     }
    },
    {
     "symbol": "L3",
     "kind": 6,
     "win": 2400,
     "positions": [
      {
       "reel": 0,
       "row": 4
      },
      {
       "reel": 1,
       "row": 4
      },
      {
       "reel": 2,
       "row": 3
      },
      {
       "reel": 2,
       "row": 4
      },
      {
       "reel": 3,
       "row": 4
      },
      {
       "reel": 4,
       "row": 1
      },
      {
       "reel": 5,
       "row": 1
      }
     ],
     "meta": {
      "ways": 12,
      "globalMult": 1,
      "winWithoutMult": 2400,
      "symbolMult": 6
     }
    },
    {
     "symbol": "L5",
     "kind": 6,
     "win": 3600,
     "positions": [
      {
       "reel": 0,
       "row": 1
      },
      {
       "reel": 1,
       "row": 1
      },
      {
       "reel": 1,
       "row": 4
      },
      {
       "reel": 2,
       "row": 3
      },
      {
       "reel": 2,
       "row": 4
      },
      {
       "reel": 3,
       "row": 4
      },
      {
       "reel": 4,
       "row": 2
      },
      {
       "reel": 5,
       "row": 1
      }
     ],
     "meta": {
      "ways": 18,
      "globalMult": 1,
      "winWithoutMult": 3600,
      "symbolMult": 6
     }
    }
   ]
  },
  {
   "index": 4,
   "type": "setWin",
   "amount": 15000,
   "winLevel": 9
  },
  {
   "type": "setTotalWin",
   "amount": 15000,
   "index": 5
  },
  {
   "type": "finalWin",
   "amount": 15000,
   "index": 6
  }
 ]
} as ShowcaseBook;

export const unlockedSlotsLevel3Book: ShowcaseBook =
	{
 "id": 113,
 "payoutMultiplier": 15000,
 "events": [
  {
   "index": 0,
   "type": "reveal",
   "board": [
    [
     {
      "name": "L3"
     },
     {
      "name": "H1"
     },
     {
      "name": "L1"
     },
     {
      "name": "L1"
     },
     {
      "name": "H5"
     },
     {
      "name": "H4"
     }
    ],
    [
     {
      "name": "H3"
     },
     {
      "name": "H5"
     },
     {
      "name": "H5"
     },
     {
      "name": "L1"
     },
     {
      "name": "W",
      "wild": true
     }
    ],
    [
     {
      "name": "L2"
     },
     {
      "name": "H5"
     },
     {
      "name": "S",
      "scatter": true
     },
     {
      "name": "H1"
     }
    ],
    [
     {
      "name": "H4"
     },
     {
      "name": "L2"
     },
     {
      "name": "W",
      "wild": true
     },
     {
      "name": "H5"
     },
     {
      "name": "H1"
     }
    ],
    [
     {
      "name": "L1"
     },
     {
      "name": "H2"
     },
     {
      "name": "H5"
     },
     {
      "name": "H1"
     },
     {
      "name": "H3"
     },
     {
      "name": "L4"
     }
    ]
   ],
   "paddingPositions": [
    4,
    26,
    145,
    143,
    108
   ],
   "gameType": "basegame",
   "anticipation": [
    0,
    0,
    0,
    1,
    2
   ]
  },
  {
   "index": 1,
   "type": "unlockedSlots",
   "label": "Unlocked Slots",
   "level": 3,
   "unlocked": [
    "bottom",
    "right",
    "left"
   ],
   "bottom": [
    {
     "reel": 1,
     "row": 4,
     "name": "H3"
    },
    {
     "reel": 3,
     "row": 4,
     "name": "H5"
    }
   ],
   "sides": [
    {
     "side": "right",
     "reel": 5,
     "cells": [
      {
       "row": 1,
       "slotRow": 0,
       "name": "W",
       "multiplier": 1
      },
      {
       "row": 2,
       "slotRow": 1,
       "name": "H4"
      },
      {
       "row": 3,
       "slotRow": 2,
       "name": "H4"
      }
     ]
    },
    {
     "side": "left",
     "reel": 6,
     "cells": [
      {
       "row": 1,
       "slotRow": 2,
       "name": "W",
       "multiplier": 1
      }
     ]
    }
   ],
   "totalWays": 1536
  },
  {
   "index": 2,
   "type": "winInfo",
   "totalWin": 15000,
   "wins": [
    {
     "symbol": "H5",
     "kind": 7,
     "win": 15000,
     "positions": [
      {
       "reel": 0,
       "row": 4
      },
      {
       "reel": 1,
       "row": 1
      },
      {
       "reel": 1,
       "row": 2
      },
      {
       "reel": 2,
       "row": 1
      },
      {
       "reel": 3,
       "row": 2
      },
      {
       "reel": 3,
       "row": 3
      },
      {
       "reel": 3,
       "row": 4
      },
      {
       "reel": 4,
       "row": 2
      },
      {
       "reel": 5,
       "row": 1
      },
      {
       "reel": 6,
       "row": 1
      }
     ],
     "meta": {
      "ways": 6,
      "globalMult": 1,
      "winWithoutMult": 15000,
      "symbolMult": 0
     }
    }
   ]
  },
  {
   "index": 3,
   "type": "setWin",
   "amount": 15000,
   "winLevel": 9
  },
  {
   "type": "setTotalWin",
   "amount": 15000,
   "index": 4
  },
  {
   "type": "finalWin",
   "amount": 15000,
   "index": 5
  }
 ]
} as ShowcaseBook;

export default [unlockedSlotsLevel1Book, unlockedSlotsLevel2Book, unlockedSlotsLevel3Book];
