// GENERATED by math-sdk/games/0_2_the_white_room/make_showcase_books.py
// Real Wild Reel books pulled from the build - each plays through the
// live Game so the reel-grow + multiplier-wild resolution is exact.
import type { BookEvent } from '../../game/typesBookEvent';

type ShowcaseBook = { id: number; payoutMultiplier: number; events: BookEvent[] };

export const wildReelSingleReel1Book: ShowcaseBook =
	{
 "id": 19001,
 "payoutMultiplier": 4200,
 "events": [
  {
   "index": 0,
   "type": "reveal",
   "board": [
    [
     {
      "name": "L5"
     },
     {
      "name": "L3"
     },
     {
      "name": "L2"
     },
     {
      "name": "L5"
     },
     {
      "name": "H2"
     },
     {
      "name": "H3"
     }
    ],
    [
     {
      "name": "H4"
     },
     {
      "name": "L3"
     },
     {
      "name": "H3"
     },
     {
      "name": "L2"
     },
     {
      "name": "H2"
     }
    ],
    [
     {
      "name": "L3"
     },
     {
      "name": "W",
      "wild": true
     },
     {
      "name": "HM",
      "mirror": true
     },
     {
      "name": "H4"
     }
    ],
    [
     {
      "name": "L2"
     },
     {
      "name": "L4"
     },
     {
      "name": "L1"
     },
     {
      "name": "W",
      "wild": true
     },
     {
      "name": "L5"
     }
    ],
    [
     {
      "name": "L1"
     },
     {
      "name": "L1"
     },
     {
      "name": "L3"
     },
     {
      "name": "L4"
     },
     {
      "name": "L3"
     },
     {
      "name": "L3"
     }
    ]
   ],
   "paddingPositions": [
    164,
    162,
    235,
    167,
    157
   ],
   "gameType": "basegame",
   "anticipation": [
    0,
    0,
    0,
    0,
    0
   ]
  },
  {
   "index": 1,
   "type": "wildReel",
   "label": "Wild Reel",
   "reels": [
    {
     "reel": 1,
     "baseRows": 3,
     "added": 1,
     "cells": [
      {
       "row": 4,
       "multiplier": 5
      }
     ]
    }
   ],
   "totalWays": 768
  },
  {
   "index": 2,
   "type": "mirrorBurst",
   "mirrors": [
    {
     "mirror": {
      "reel": 2,
      "row": 2
     },
     "reflected": [
      {
       "reel": 3,
       "row": 1,
       "apparitions": 2
      }
     ],
     "mirrorBecomes": {
      "name": "W"
     }
    }
   ],
   "totalWays": 1024
  },
  {
   "index": 3,
   "type": "winInfo",
   "totalWin": 4200,
   "wins": [
    {
     "symbol": "H2",
     "kind": 4,
     "win": 1500,
     "positions": [
      {
       "reel": 0,
       "row": 4
      },
      {
       "reel": 1,
       "row": 4
      },
      {
       "reel": 2,
       "row": 1
      },
      {
       "reel": 2,
       "row": 2
      },
      {
       "reel": 3,
       "row": 3
      }
     ],
     "meta": {
      "ways": 10,
      "globalMult": 1,
      "winWithoutMult": 1500,
      "symbolMult": 5
     }
    },
    {
     "symbol": "L2",
     "kind": 4,
     "win": 480,
     "positions": [
      {
       "reel": 0,
       "row": 2
      },
      {
       "reel": 1,
       "row": 3
      },
      {
       "reel": 1,
       "row": 4
      },
      {
       "reel": 2,
       "row": 1
      },
      {
       "reel": 2,
       "row": 2
      },
      {
       "reel": 3,
       "row": 3
      }
     ],
     "meta": {
      "ways": 12,
      "globalMult": 1,
      "winWithoutMult": 480,
      "symbolMult": 5
     }
    },
    {
     "symbol": "L3",
     "kind": 5,
     "win": 1920,
     "positions": [
      {
       "reel": 0,
       "row": 1
      },
      {
       "reel": 1,
       "row": 1
      },
      {
       "reel": 1,
       "row": 4
      },
      {
       "reel": 2,
       "row": 1
      },
      {
       "reel": 2,
       "row": 2
      },
      {
       "reel": 3,
       "row": 3
      },
      {
       "reel": 4,
       "row": 2
      },
      {
       "reel": 4,
       "row": 4
      }
     ],
     "meta": {
      "ways": 24,
      "globalMult": 1,
      "winWithoutMult": 1920,
      "symbolMult": 5
     }
    },
    {
     "symbol": "L5",
     "kind": 4,
     "win": 300,
     "positions": [
      {
       "reel": 0,
       "row": 3
      },
      {
       "reel": 1,
       "row": 4
      },
      {
       "reel": 2,
       "row": 1
      },
      {
       "reel": 2,
       "row": 2
      },
      {
       "reel": 3,
       "row": 3
      }
     ],
     "meta": {
      "ways": 10,
      "globalMult": 1,
      "winWithoutMult": 300,
      "symbolMult": 5
     }
    }
   ]
  },
  {
   "index": 4,
   "type": "setWin",
   "amount": 4200,
   "winLevel": 7
  },
  {
   "index": 5,
   "type": "setTotalWin",
   "amount": 4200
  },
  {
   "index": 6,
   "type": "finalWin",
   "amount": 4200
  }
 ]
} as ShowcaseBook;

export const wildReelSingleReel2Book: ShowcaseBook =
	{
 "id": 638,
 "payoutMultiplier": 1200,
 "events": [
  {
   "index": 0,
   "type": "reveal",
   "board": [
    [
     {
      "name": "L5"
     },
     {
      "name": "L4"
     },
     {
      "name": "H5"
     },
     {
      "name": "H5"
     },
     {
      "name": "L5"
     },
     {
      "name": "H5"
     }
    ],
    [
     {
      "name": "L3"
     },
     {
      "name": "L4"
     },
     {
      "name": "L3"
     },
     {
      "name": "L2"
     },
     {
      "name": "L3"
     }
    ],
    [
     {
      "name": "H5"
     },
     {
      "name": "H2"
     },
     {
      "name": "H3"
     },
     {
      "name": "L5"
     }
    ],
    [
     {
      "name": "H2"
     },
     {
      "name": "L2"
     },
     {
      "name": "L4"
     },
     {
      "name": "L1"
     },
     {
      "name": "W",
      "wild": true
     }
    ],
    [
     {
      "name": "L4"
     },
     {
      "name": "H3"
     },
     {
      "name": "H5"
     },
     {
      "name": "H1"
     },
     {
      "name": "L4"
     },
     {
      "name": "L4"
     }
    ]
   ],
   "paddingPositions": [
    157,
    100,
    175,
    166,
    37
   ],
   "gameType": "basegame",
   "anticipation": [
    0,
    0,
    0,
    0,
    0
   ]
  },
  {
   "index": 1,
   "type": "wildReel",
   "label": "Wild Reel",
   "reels": [
    {
     "reel": 2,
     "baseRows": 2,
     "added": 2,
     "cells": [
      {
       "row": 3,
       "multiplier": 10
      },
      {
       "row": 4,
       "multiplier": 5
      }
     ]
    }
   ],
   "totalWays": 2448
  },
  {
   "index": 2,
   "type": "winInfo",
   "totalWin": 1200,
   "wins": [
    {
     "symbol": "L4",
     "kind": 5,
     "win": 1200,
     "positions": [
      {
       "reel": 0,
       "row": 1
      },
      {
       "reel": 1,
       "row": 1
      },
      {
       "reel": 2,
       "row": 3
      },
      {
       "reel": 2,
       "row": 4
      },
      {
       "reel": 3,
       "row": 2
      },
      {
       "reel": 4,
       "row": 4
      }
     ],
     "meta": {
      "ways": 15,
      "globalMult": 1,
      "winWithoutMult": 1200,
      "symbolMult": 15
     }
    }
   ]
  },
  {
   "index": 3,
   "type": "setWin",
   "amount": 1200,
   "winLevel": 5
  },
  {
   "index": 4,
   "type": "setTotalWin",
   "amount": 1200
  },
  {
   "index": 5,
   "type": "finalWin",
   "amount": 1200
  }
 ]
} as ShowcaseBook;

export const wildReelDoubleBook: ShowcaseBook =
	{
 "id": 1724,
 "payoutMultiplier": 12000,
 "events": [
  {
   "index": 0,
   "type": "reveal",
   "board": [
    [
     {
      "name": "H3"
     },
     {
      "name": "L2"
     },
     {
      "name": "H5"
     },
     {
      "name": "L5"
     },
     {
      "name": "L1"
     },
     {
      "name": "L2"
     }
    ],
    [
     {
      "name": "H5"
     },
     {
      "name": "HM",
      "mirror": true
     },
     {
      "name": "L3"
     },
     {
      "name": "HM",
      "mirror": true
     },
     {
      "name": "L1"
     }
    ],
    [
     {
      "name": "L1"
     },
     {
      "name": "H4"
     },
     {
      "name": "H2"
     },
     {
      "name": "L1"
     }
    ],
    [
     {
      "name": "L4"
     },
     {
      "name": "H3"
     },
     {
      "name": "L3"
     },
     {
      "name": "L4"
     },
     {
      "name": "L4"
     }
    ],
    [
     {
      "name": "L4"
     },
     {
      "name": "L1"
     },
     {
      "name": "H2"
     },
     {
      "name": "H5"
     },
     {
      "name": "H2"
     },
     {
      "name": "L1"
     }
    ]
   ],
   "paddingPositions": [
    24,
    213,
    230,
    199,
    7
   ],
   "gameType": "basegame",
   "anticipation": [
    0,
    0,
    0,
    0,
    0
   ]
  },
  {
   "index": 1,
   "type": "wildReel",
   "label": "Wild Reel",
   "reels": [
    {
     "reel": 2,
     "baseRows": 2,
     "added": 2,
     "cells": [
      {
       "row": 3,
       "multiplier": 2
      },
      {
       "row": 4,
       "multiplier": 1
      }
     ]
    },
    {
     "reel": 3,
     "baseRows": 3,
     "added": 1,
     "cells": [
      {
       "row": 4,
       "multiplier": 2
      }
     ]
    }
   ],
   "totalWays": 1200
  },
  {
   "index": 2,
   "type": "mirrorBurst",
   "mirrors": [
    {
     "mirror": {
      "reel": 1,
      "row": 3
     },
     "reflected": [
      {
       "reel": 0,
       "row": 4,
       "apparitions": 3
      },
      {
       "reel": 0,
       "row": 2,
       "apparitions": 3
      }
     ],
     "mirrorBecomes": {
      "name": "H5"
     }
    },
    {
     "mirror": {
      "reel": 1,
      "row": 1
     },
     "reflected": [
      {
       "reel": 0,
       "row": 1,
       "apparitions": 3
      },
      {
       "reel": 0,
       "row": 2,
       "apparitions": 4
      }
     ],
     "mirrorBecomes": {
      "name": "H5"
     }
    }
   ],
   "totalWays": 3300
  },
  {
   "index": 3,
   "type": "winInfo",
   "totalWin": 12000,
   "wins": [
    {
     "symbol": "H5",
     "kind": 5,
     "win": 12000,
     "positions": [
      {
       "reel": 0,
       "row": 2
      },
      {
       "reel": 1,
       "row": 1
      },
      {
       "reel": 1,
       "row": 3
      },
      {
       "reel": 2,
       "row": 3
      },
      {
       "reel": 2,
       "row": 4
      },
      {
       "reel": 3,
       "row": 4
      },
      {
       "reel": 4,
       "row": 3
      }
     ],
     "meta": {
      "ways": 48,
      "globalMult": 1,
      "winWithoutMult": 12000,
      "symbolMult": 4
     }
    }
   ]
  },
  {
   "index": 4,
   "type": "setWin",
   "amount": 12000,
   "winLevel": 9
  },
  {
   "index": 5,
   "type": "setTotalWin",
   "amount": 12000
  },
  {
   "index": 6,
   "type": "finalWin",
   "amount": 12000
  }
 ]
} as ShowcaseBook;

export const wildReelTripleBook: ShowcaseBook =
	{
 "id": 4729,
 "payoutMultiplier": 1960,
 "events": [
  {
   "index": 0,
   "type": "reveal",
   "board": [
    [
     {
      "name": "H5"
     },
     {
      "name": "L1"
     },
     {
      "name": "H4"
     },
     {
      "name": "L1"
     },
     {
      "name": "S",
      "scatter": true
     },
     {
      "name": "H5"
     }
    ],
    [
     {
      "name": "H5"
     },
     {
      "name": "H3"
     },
     {
      "name": "S",
      "scatter": true
     },
     {
      "name": "H5"
     },
     {
      "name": "H3"
     }
    ],
    [
     {
      "name": "L1"
     },
     {
      "name": "S",
      "scatter": true
     },
     {
      "name": "L5"
     },
     {
      "name": "H5"
     }
    ],
    [
     {
      "name": "L4"
     },
     {
      "name": "L3"
     },
     {
      "name": "H4"
     },
     {
      "name": "H4"
     },
     {
      "name": "L1"
     }
    ],
    [
     {
      "name": "L3"
     },
     {
      "name": "L4"
     },
     {
      "name": "H4"
     },
     {
      "name": "L5"
     },
     {
      "name": "H1"
     },
     {
      "name": "L1"
     }
    ]
   ],
   "paddingPositions": [
    199,
    17,
    139,
    48,
    164
   ],
   "gameType": "basegame",
   "anticipation": [
    0,
    0,
    1,
    2,
    3
   ]
  },
  {
   "index": 1,
   "type": "wildReel",
   "label": "Wild Reel",
   "reels": [
    {
     "reel": 1,
     "baseRows": 3,
     "added": 1,
     "cells": [
      {
       "row": 4,
       "multiplier": 1
      }
     ]
    },
    {
     "reel": 2,
     "baseRows": 2,
     "added": 2,
     "cells": [
      {
       "row": 3,
       "multiplier": 1
      },
      {
       "row": 4,
       "multiplier": 1
      }
     ]
    },
    {
     "reel": 3,
     "baseRows": 3,
     "added": 1,
     "cells": [
      {
       "row": 4,
       "multiplier": 1
      }
     ]
    }
   ],
   "totalWays": 1024
  },
  {
   "index": 2,
   "type": "winInfo",
   "totalWin": 1960,
   "wins": [
    {
     "symbol": "H4",
     "kind": 5,
     "win": 1800,
     "positions": [
      {
       "reel": 0,
       "row": 2
      },
      {
       "reel": 1,
       "row": 4
      },
      {
       "reel": 2,
       "row": 3
      },
      {
       "reel": 2,
       "row": 4
      },
      {
       "reel": 3,
       "row": 2
      },
      {
       "reel": 3,
       "row": 3
      },
      {
       "reel": 3,
       "row": 4
      },
      {
       "reel": 4,
       "row": 2
      }
     ],
     "meta": {
      "ways": 6,
      "globalMult": 1,
      "winWithoutMult": 1800,
      "symbolMult": 0
     }
    },
    {
     "symbol": "L1",
     "kind": 4,
     "win": 160,
     "positions": [
      {
       "reel": 0,
       "row": 1
      },
      {
       "reel": 0,
       "row": 3
      },
      {
       "reel": 1,
       "row": 4
      },
      {
       "reel": 2,
       "row": 3
      },
      {
       "reel": 2,
       "row": 4
      },
      {
       "reel": 3,
       "row": 4
      }
     ],
     "meta": {
      "ways": 4,
      "globalMult": 1,
      "winWithoutMult": 160,
      "symbolMult": 0
     }
    }
   ]
  },
  {
   "index": 3,
   "type": "setWin",
   "amount": 1960,
   "winLevel": 6
  },
  {
   "type": "setTotalWin",
   "amount": 1960,
   "index": 4
  },
  {
   "type": "finalWin",
   "amount": 1960,
   "index": 5
  }
 ]
} as ShowcaseBook;

export default [wildReelSingleReel1Book, wildReelSingleReel2Book, wildReelDoubleBook, wildReelTripleBook];
