"""Madam Mirror - GENERATED by game-builder (do not edit by hand).

Regenerate: node game-builder/src/cli.mjs gen-math madam_mirror
Source of truth: game-builder/config/madam_mirror.config.json
"""

import os
from src.config.config import Config
from src.config.distributions import Distribution
from src.config.betmode import BetMode


class GameConfig(Config):
    """Game specific configuration class."""

    _instance = None

    def __new__(cls):
        if cls._instance is None:
            cls._instance = super().__new__(cls)
        return cls._instance

    def __init__(self):
        super().__init__()
        self.game_id = "0_1_madam_mirror"
        self.provider_name = "dramastudios"
        self.game_name = "madam_mirror"
        self.provider_number = 0
        self.working_name = "Madam Mirror"
        self.wincap = 30000.0
        self.win_type = "ways"
        self.rtp = 0.965
        self.construct_paths()

        # Game Dimensions
        self.num_reels = 5
        self.num_rows = [4, 4, 4, 4, 4]

        self.paytable = {
            (5, "H1"): 10, (4, "H1"): 3, (3, "H1"): 1,
            (5, "H2"): 5, (4, "H2"): 1.5, (3, "H2"): 0.6,
            (5, "H3"): 4, (4, "H3"): 1.2, (3, "H3"): 0.5,
            (5, "H4"): 3, (4, "H4"): 1, (3, "H4"): 0.4,
            (5, "H5"): 2.5, (4, "H5"): 0.8, (3, "H5"): 0.3,
            (5, "L1"): 1.2, (4, "L1"): 0.4, (3, "L1"): 0.2,
            (5, "L2"): 1.2, (4, "L2"): 0.4, (3, "L2"): 0.2,
            (5, "L3"): 0.8, (4, "L3"): 0.3, (3, "L3"): 0.1,
            (5, "L4"): 0.8, (4, "L4"): 0.3, (3, "L4"): 0.1,
            (5, "L5"): 0.8, (4, "L5"): 0.3, (3, "L5"): 0.1,
        }

        self.include_padding = True
        self.special_symbols = {"wild": ["W"], "scatter": ["S"], "multiplier": [], "mirror": ["HM"], "eye": ["ME"], "ttl": []}

        self.freespin_triggers = {
            self.basegame_type: {3: 8, 4: 10, 5: 12},
            self.freegame_type: {2: 3, 3: 3, 4: 3, 5: 3},
        }
        self.anticipation_triggers = {
            self.basegame_type: min(self.freespin_triggers[self.basegame_type].keys()) - 1,
            self.freegame_type: min(self.freespin_triggers[self.freegame_type].keys()) - 1,
        }

        self.bonus_levels = {1: {"name": "THE_SEANCE", "mirror_chance": 0.4, "split_count_weights": {1: 50, 2: 26, 3: 13, 4: 7, 5: 3, 6: 1}, "lifetime": 1, "stacking": False}, 2: {"name": "THE_OTHER_SIDE", "mirror_chance": 0.45, "split_count_weights": {1: 45, 2: 27, 3: 15, 4: 8, 5: 4, 6: 2}, "lifetime": 2, "stacking": True}, 3: {"name": "BLOOD_MOON", "mirror_chance": 0.5, "split_count_weights": {1: 40, 2: 28, 3: 16, 4: 9, 5: 5, 6: 2}, "lifetime": None, "stacking": True}}
        self.scatter_to_level = {3: 1, 4: 2, 5: 3}

        self.mirror_config = {"probability": {self.basegame_type: 0.14}, "mirror_count_weights": {1: 80, 2: 17, 3: 3}, "allowed_reels": [1, 2, 3], "split_count_weights": {1: 52, 2: 26, 3: 12, 4: 6, 5: 3, 6: 1}, "apparition_weights": {2: 60, 3: 30, 4: 10}}
        self.eye_config = {"probability": {self.basegame_type: 0.05, self.freegame_type: 0.08}}

        # Reels
        reels = {"BR0": "BR0.csv", "FR0": "FR0.csv", "FRWCAP": "FRWCAP.csv", "BRWCAP": "BRWCAP.csv"}
        self.reels = {}
        for r, fn in reels.items():
            self.reels[r] = self.read_reels_csv(os.path.join(self.reels_path, fn))

        self.padding_reels[self.basegame_type] = self.reels["BR0"]
        self.padding_reels[self.freegame_type] = self.reels["FR0"]

        def wincap_condition(scatter_triggers):
            return {
                "reel_weights": {self.basegame_type: {"BR0": 1}, self.freegame_type: {"FR0": 1, "FRWCAP": 8}},
                "force_wincap": True,
                "force_freegame": True,
                "force_mirrors": True,
                "scatter_triggers": scatter_triggers,
            }

        base_wincap_condition = {
            "reel_weights": {self.basegame_type: {"BRWCAP": 1}},
            "force_wincap": True,
            "force_freegame": False,
            "force_mirrors": True,
        }
        zero_condition = {"reel_weights": {self.basegame_type: {"BR0": 1}}, "force_wincap": False, "force_freegame": False}
        basegame_condition = {"reel_weights": {self.basegame_type: {"BR0": 1}}, "force_wincap": False, "force_freegame": False}

        def freegame_condition(scatter_triggers):
            return {
                "reel_weights": {self.basegame_type: {"BR0": 1}, self.freegame_type: {"FR0": 1}},
                "force_wincap": False,
                "force_freegame": True,
                "scatter_triggers": scatter_triggers,
            }

        mode_maxwin = 30000
        self.mode_rtps = {"base": 0.962, "ante": 0.962, "feature1": 0.965, "feature2": 0.965, "feature3": 0.965, "bonus1": 0.965, "bonus2": 0.966, "bonus3": 0.9665}

        def ante_condition(base_condition):
            condition = dict(base_condition)
            condition["force_scatter_reel"] = 0
            return condition

        def mirror_condition(base_condition, min_mirrors):
            condition = dict(base_condition)
            condition["force_mirror_min"] = min_mirrors
            return condition

        self.bet_modes = [
            BetMode(
                name="base",
                cost=1.00,
                rtp=self.mode_rtps["base"],
                max_win=mode_maxwin,
                auto_close_disabled=False,
                is_feature=True,
                is_buybonus=False,
                distributions=[
                    Distribution(criteria="wincap", quota=0.001, win_criteria=mode_maxwin, conditions=base_wincap_condition),
                    Distribution(criteria="freegame", quota=0.08, conditions=freegame_condition({3: 100, 4: 25, 5: 6})),
                    Distribution(criteria="0", quota=0.549, win_criteria=0.0, conditions=zero_condition),
                    Distribution(criteria="basegame", quota=0.37, conditions=basegame_condition),
                ],
            ),
            BetMode(
                name="ante",
                cost=1.25,
                rtp=self.mode_rtps["ante"],
                max_win=mode_maxwin,
                auto_close_disabled=False,
                is_feature=True,
                is_buybonus=False,
                distributions=[
                    Distribution(criteria="wincap", quota=0.001, win_criteria=mode_maxwin, conditions=ante_condition(base_wincap_condition)),
                    Distribution(criteria="freegame", quota=0.14, conditions=ante_condition(freegame_condition({3: 100, 4: 25, 5: 6}))),
                    Distribution(criteria="0", quota=0.539, win_criteria=0.0, conditions=ante_condition(zero_condition)),
                    Distribution(criteria="basegame", quota=0.32, conditions=ante_condition(basegame_condition)),
                ],
            ),
            BetMode(
                name="feature1",
                cost=10.00,
                rtp=self.mode_rtps["feature1"],
                max_win=mode_maxwin,
                auto_close_disabled=False,
                is_feature=True,
                is_buybonus=False,
                distributions=[
                    Distribution(criteria="wincap", quota=0.001, win_criteria=mode_maxwin, conditions=mirror_condition(base_wincap_condition, 1)),
                    Distribution(criteria="freegame", quota=0.02, conditions=mirror_condition(freegame_condition({3: 100, 4: 25, 5: 6}), 1)),
                    Distribution(criteria="basegame", quota=0.979, conditions=mirror_condition(basegame_condition, 1)),
                ],
            ),
            BetMode(
                name="feature2",
                cost=20.00,
                rtp=self.mode_rtps["feature2"],
                max_win=mode_maxwin,
                auto_close_disabled=False,
                is_feature=True,
                is_buybonus=False,
                distributions=[
                    Distribution(criteria="wincap", quota=0.001, win_criteria=mode_maxwin, conditions=mirror_condition(base_wincap_condition, 2)),
                    Distribution(criteria="freegame", quota=0.02, conditions=mirror_condition(freegame_condition({3: 100, 4: 25, 5: 6}), 2)),
                    Distribution(criteria="basegame", quota=0.979, conditions=mirror_condition(basegame_condition, 2)),
                ],
            ),
            BetMode(
                name="feature3",
                cost=40.00,
                rtp=self.mode_rtps["feature3"],
                max_win=mode_maxwin,
                auto_close_disabled=False,
                is_feature=True,
                is_buybonus=False,
                distributions=[
                    Distribution(criteria="wincap", quota=0.001, win_criteria=mode_maxwin, conditions=mirror_condition(base_wincap_condition, 3)),
                    Distribution(criteria="freegame", quota=0.02, conditions=mirror_condition(freegame_condition({3: 100, 4: 25, 5: 6}), 3)),
                    Distribution(criteria="basegame", quota=0.979, conditions=mirror_condition(basegame_condition, 3)),
                ],
            ),
            BetMode(
                name="bonus1",
                cost=100.00,
                rtp=self.mode_rtps["bonus1"],
                max_win=mode_maxwin,
                auto_close_disabled=False,
                is_feature=False,
                is_buybonus=True,
                distributions=[
                    Distribution(criteria="wincap", quota=0.001, win_criteria=mode_maxwin, conditions=wincap_condition({3: 1})),
                    Distribution(criteria="freegame", quota=0.999, conditions=freegame_condition({3: 1})),
                ],
            ),
            BetMode(
                name="bonus2",
                cost=400.00,
                rtp=self.mode_rtps["bonus2"],
                max_win=mode_maxwin,
                auto_close_disabled=False,
                is_feature=False,
                is_buybonus=True,
                distributions=[
                    Distribution(criteria="wincap", quota=0.001, win_criteria=mode_maxwin, conditions=wincap_condition({4: 1})),
                    Distribution(criteria="freegame", quota=0.999, conditions=freegame_condition({4: 1})),
                ],
            ),
            BetMode(
                name="bonus3",
                cost=1000.00,
                rtp=self.mode_rtps["bonus3"],
                max_win=mode_maxwin,
                auto_close_disabled=False,
                is_feature=False,
                is_buybonus=True,
                distributions=[
                    Distribution(criteria="wincap", quota=0.004, win_criteria=mode_maxwin, conditions=wincap_condition({5: 1})),
                    Distribution(criteria="freegame", quota=0.996, conditions=freegame_condition({5: 1})),
                ],
            )
        ]
