// GENERATED by game-builder (node game-builder/src/cli.mjs gen-frontend).
// Source of truth: game-builder/config/<game>.config.json. Do not edit by hand.
// Hand-synced for TOMBSTONE REBORN (6 reels, 3/4/4/2/2/1, 99,999x).
export default {
	providerName: 'dramastudios',
	gameName: 'tombstone_reborn',
	gameID: '0_3_tombstone_reborn',
	rtp: 0.965,
	numReels: 6,
	numRows: [3, 4, 4, 2, 2, 1],
	betModes: {
		base: {
			cost: 1.0,
			feature: true,
			buyBonus: false,
			rtp: 0.965,
			max_win: 99999,
		},
		bonus_small: {
			cost: 80.0,
			feature: false,
			buyBonus: true,
			rtp: 0.965,
			max_win: 99999,
		},
		bonus_super: {
			cost: 1000.0,
			feature: false,
			buyBonus: true,
			rtp: 0.965,
			max_win: 99999,
		},
	},
	symbols: {
		W: {
			paytable: [{ '6': 10 }],
			special_properties: ['wild'],
		},
		STRETCH: {
			paytable: null,
			special_properties: ['stretch'],
		},
		SPLIT: {
			paytable: null,
			special_properties: ['split'],
		},
		CLONE: {
			paytable: null,
			special_properties: ['clone'],
		},
		HM: {
			paytable: null,
			special_properties: ['mirror'],
		},
		ME: {
			paytable: null,
			special_properties: ['eye'],
		},
		S: {
			paytable: null,
			special_properties: ['scatter'],
		},
		H1: {
			paytable: [{ '6': 5 }, { '5': 1.5 }, { '4': 0.5 }, { '3': 0.2 }],
		},
		H2: {
			paytable: [{ '6': 3 }, { '5': 1 }, { '4': 0.4 }, { '3': 0.2 }],
		},
		H3: {
			paytable: [{ '6': 2.5 }, { '5': 0.8 }, { '4': 0.3 }, { '3': 0.1 }],
		},
		H4: {
			paytable: [{ '6': 2 }, { '5': 0.6 }, { '4': 0.3 }, { '3': 0.1 }],
		},
		H5: {
			paytable: [{ '6': 1.5 }, { '5': 0.5 }, { '4': 0.2 }, { '3': 0.1 }],
		},
		L1: {
			paytable: [{ '6': 1 }, { '5': 0.4 }, { '4': 0.2 }, { '3': 0.1 }],
		},
		L2: {
			paytable: [{ '6': 1 }, { '5': 0.4 }, { '4': 0.2 }, { '3': 0.1 }],
		},
		L3: {
			paytable: [{ '6': 0.8 }, { '5': 0.3 }, { '4': 0.1 }, { '3': 0.1 }],
		},
		L4: {
			paytable: [{ '6': 0.8 }, { '5': 0.3 }, { '4': 0.1 }, { '3': 0.1 }],
		},
		L5: {
			paytable: [{ '6': 0.6 }, { '5': 0.2 }, { '4': 0.1 }, { '3': 0.1 }],
		},
	},
	paddingReels: {
		basegame: '',
		freegame: '',
		superspingame: '',
	},
};
