/** Generated by tools/bake_gunsmoke_props.py — re-run the baker to refresh. */
export const GUNSMOKE_ART = {
	gun: {
		width: 196.0,
		height: 176.0,
		anchorX: 0.2429,
		anchorY: 0.5405,
		muzzleX: 0.9643,
		muzzleY: 0.0682,
		nativeBarrel: -0.5315,
	},
	bullets: [
		{ key: 'gunsmokeBulletA', native: -0.7369 },
		{ key: 'gunsmokeBulletB', native: -0.8785 },
		{ key: 'gunsmokeBulletC', native: -0.8608 },
	],
} as const;
