/** Generated by tools/bake_saloon_room.py — do not edit by hand. */

export const SCENE_ART = { width: 1679, height: 937 } as const;

export type SaloonLamp = {
	/** Chain mount in SCENE_ART pixels. */
	x: number;
	y: number;
	width: number;
	height: number;
	/** Pivot inside the full lamp layer (0–1), at the chain mount. */
	anchorX: number;
	anchorY: number;
};

export const SALOON_LAMPS: { L: SaloonLamp; R: SaloonLamp } = {
	L: {
		x: 149.69,
		y: -21.41,
		width: 976,
		height: 931,
		anchorX: 0.4804,
		anchorY: 0,
	},
	R: {
		x: 1516.31,
		y: -21.41,
		width: 976,
		height: 931,
		anchorX: 0.4938,
		anchorY: 0,
	},
};
