import { createSound } from 'utils-sound';

// Base bed is the Howler sprite. Small / big bonus beds are standalone loops
// (bonusgame 1 / 2) played by bonusBgm.ts — not packed into the SFX atlas.
export type MusicName =
	| 'bgm_main'
	| 'bgm_bonus_small'
	| 'bgm_bonus_super'
	// six escalating western celebration beds, one per win-level stage
	| 'bgm_celeb_1'
	| 'bgm_celeb_2'
	| 'bgm_celeb_3'
	| 'bgm_celeb_4'
	| 'bgm_celeb_5'
	| 'bgm_celeb_6';

export type SoundEffectName =
	| 'jng_intro_fs'
	| 'sfx_btn_general'
	| 'sfx_btn_spin'
	| 'sfx_fs_respins'
	| 'sfx_multiplier_combine_a'
	| 'sfx_multiplier_combine_b'
	| 'sfx_multiplier_explosion_a'
	| 'sfx_multiplier_explosion_b'
	| 'sfx_multiplier_explosion_c'
	| 'sfx_multiplier_landing'
	| 'sfx_multiplier_reset'
	| 'sfx_multiplier_up'
	| 'sfx_multiplier_update'
	| 'sfx_multiplier_win'
	| 'sfx_reel_stop_1'
	| 'sfx_reel_stop_2'
	| 'sfx_reel_stop_3'
	| 'sfx_reel_stop_4'
	| 'sfx_reel_stop_5'
	| 'sfx_royals_landing'
	| 'sfx_scatter_reveal'
	| 'sfx_scatter_stop_1'
	| 'sfx_scatter_stop_2'
	| 'sfx_scatter_stop_3'
	| 'sfx_scatter_stop_4'
	| 'sfx_scatter_stop_5'
	| 'sfx_scatter_win'
	| 'sfx_scatter_win_v2'
	| 'sfx_superfreespin'
	| 'sfx_symbols_landing'
	| 'sfx_ui_click'
	| 'sfx_ui_click_heavy'
	| 'sfx_ui_click_soft'
	| 'sfx_wild_explode'
	| 'sfx_tombstone_toll'
	| 'sfx_thunder'
	| 'sfx_cell_seal_expand'
	| 'sfx_cell_seal_harden'
	| 'sfx_cell_seal_h3_expand'
	| 'sfx_bullet_wood'
	| 'sfx_bullet_ricochet'
	| 'sfx_gunshot'
	| 'sfx_muzzle'
	| 'sfx_lamp_smash'
	| 'sfx_celeb_stamp'
	| 'sfx_shot_reveal'
	| 'sfx_wild_land'
	| 'sfx_lane_card'
	| 'sfx_lane_wild'
	| 'sfx_split'
	| 'sfx_split_hit'
	| 'sfx_split_bite'
	| 'sfx_split_thunk'
	| 'sfx_split_blood'
	| 'sfx_split_drag'
	| 'sfx_ways_stretch'
	| 'sfx_split_seam_tear'
	// fire on linked cells / reel edges: ignite one-shot, sustained burn bed,
	// escalation flare, burn-out tail
	| 'sfx_fire_ignite'
	| 'sfx_fire_loop'
	| 'sfx_fire_flare'
	| 'sfx_fire_out'
	| 'sfx_lock_snap'
	| 'sfx_lock_release'
	| 'sfx_fuse_crackle'
	| 'sfx_ember_whoosh'
	| 'sfx_reel_nudge'
	| 'sfx_gunsmoke'
	| 'sfx_tombstone_open'
	| 'sfx_special_hit'
	| 'sfx_bounty'
	// digUp: three genuinely different takes so staggered multi-cell digs never
	// sound copy-pasted, plus the handle settling once the blades are planted
	| 'sfx_shovel_strike_1'
	| 'sfx_shovel_strike_2'
	| 'sfx_shovel_strike_3'
	| 'sfx_shovel_settle'
	// bonus-entry banner: one sting per bought mode, then the hand-off accent as
	// the banner clears into the single enhanced spin the player paid for
	| 'sfx_bonus_entry_small'
	| 'sfx_bonus_entry_super'
	| 'sfx_bonus_handoff'
	| 'sfx_celeb_whoosh'
	| 'sfx_celeb_swell'
	| 'sfx_celeb_wobble'
	| 'sfx_celeb_buildup'
	| 'sfx_celeb_maxslam'
	| 'sfx_celeb_hit'
	| 'sfx_celeb_whoosh_hi'
	| 'sfx_celeb_whoosh_lo'
	| 'sfx_winlevel_end'
	| 'sfx_winlevel_nice'
	| 'sfx_winlevel_small'
	| 'sfx_win_ways'
	| 'sfx_winlevel_standard'
	| 'sfx_winlevel_substantial'
	| 'sfx_youwon_panel'
	| 'tumble_win_1'
	| 'tumble_win_2'
	| 'tumble_win_3'
	| 'tumble_win_4'
	| 'tumble_win_5';

export type SoundName = MusicName | SoundEffectName;

const sound = createSound<SoundName>();

export { sound };
