/** Live overlay seats from assets/spines/western_scene. Regenerated by tools/sync_western_scene_seats.py. */
export const WESTERN_SCENE_SEATS = {
	cloudHomeX: 592.5,
	barrelGlow: {
		x: 2615.28,
		y: 1084.1,
		w: 840.0,
		h: 840.0,
	},
} as const;
