"""Bake the live saloon room from the fire-frame lady-spine.

The PSD plate has NO lanterns. lamp_L / lamp_R are the FULL hanging-lamp
layers (chain, body, flame, glow) — do NOT silhouette-crop them. We only
drop fully transparent margin so the file is not a 3201x3053 empty canvas.

Placement matches lady.json: bone = chain mount, attachment = full layer.
"""

from __future__ import annotations

import json
import os

from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
APP = os.path.normpath(os.path.join(HERE, ".."))
SRC_IMG = r"C:\Users\Emex33\Documents\fire frame vfx\lady-spine\lady\images"
SRC_JSON = r"C:\Users\Emex33\Documents\fire frame vfx\lady-spine\lady\lady.json"

DOC_W = 5504
DOC_H = 3072
OUT_W = 1679
OUT_H = 937
SCALE = OUT_W / DOC_W

SPRITE_DESTS = [
    os.path.join(APP, "assets", "sprites", "scene"),
    os.path.join(APP, "assets-src", "assets", "sprites", "scene"),
    os.path.join(APP, "static", "assets", "sprites", "scene"),
]


def _chain_art(bone: dict) -> tuple[float, float]:
    """Spine Y-up centre origin → art-space top-left Y-down."""
    return (
        round(OUT_W / 2 + bone["x"] * SCALE, 2),
        round(OUT_H / 2 - bone["y"] * SCALE, 2),
    )


def _full_lamp(src: Image.Image, attach: dict, bone: dict) -> tuple[Image.Image, dict]:
    """Downscale the whole layer. Trim only alpha==0. Pivot at the chain bone."""
    rgba = src.convert("RGBA")
    out_w = max(1, round(rgba.width * SCALE))
    out_h = max(1, round(rgba.height * SCALE))
    small = rgba.resize((out_w, out_h), Image.LANCZOS)

    # Image centre in Spine world, then to art pixels.
    img_cx = (bone["x"] + attach.get("x", 0)) * SCALE
    img_cy = (bone["y"] + attach.get("y", 0)) * SCALE
    art_left = OUT_W / 2 + img_cx - out_w / 2
    art_top = OUT_H / 2 - img_cy - out_h / 2

    alpha = small.split()[3]
    bbox = alpha.point(lambda v: 255 if v > 0 else 0).getbbox()
    if bbox is None:
        raise RuntimeError("lamp layer is empty")
    trimmed = small.crop(bbox)
    ox, oy = bbox[0], bbox[1]
    art_left += ox
    art_top += oy

    chain_x, chain_y = _chain_art(bone)
    tw, th = trimmed.size
    layout = {
        "x": chain_x,
        "y": chain_y,
        "width": tw,
        "height": th,
        "anchorX": round((chain_x - art_left) / tw, 4),
        "anchorY": max(0.0, round((chain_y - art_top) / th, 4)),
    }
    return trimmed, layout


def _write_ts(layout: dict) -> None:
    path = os.path.join(APP, "src", "game", "saloonLamps.ts")
    l = layout["L"]
    r = layout["R"]
    body = f"""/** Generated by tools/bake_saloon_room.py — do not edit by hand. */

export const SCENE_ART = {{ width: {OUT_W}, height: {OUT_H} }} as const;

export type SaloonLamp = {{
	/** Chain mount in SCENE_ART pixels. */
	x: number;
	y: number;
	width: number;
	height: number;
	/** Pivot inside the full lamp layer (0–1), at the chain mount. */
	anchorX: number;
	anchorY: number;
}};

export const SALOON_LAMPS: {{ L: SaloonLamp; R: SaloonLamp }} = {{
	L: {{
		x: {l['x']},
		y: {l['y']},
		width: {l['width']},
		height: {l['height']},
		anchorX: {l['anchorX']},
		anchorY: {l['anchorY']},
	}},
	R: {{
		x: {r['x']},
		y: {r['y']},
		width: {r['width']},
		height: {r['height']},
		anchorX: {r['anchorX']},
		anchorY: {r['anchorY']},
	}},
}};
"""
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write(body)
    print(f"wrote {path}")


def main() -> None:
    raw = json.load(open(SRC_JSON, encoding="utf-8"))
    bones = {b["name"]: b for b in raw["bones"]}
    attaches = raw["skins"]["default"]
    if "lamp_L" not in attaches or "lamp_R" not in attaches:
        raise RuntimeError("lady-spine is missing lamp attachments")

    bg = Image.open(os.path.join(SRC_IMG, "bg.png")).convert("RGBA")
    plate = bg.resize((OUT_W, OUT_H), Image.LANCZOS)

    layout: dict = {}
    crops: dict[str, Image.Image] = {}
    for key, side in (("lamp_L", "L"), ("lamp_R", "R")):
        src = Image.open(os.path.join(SRC_IMG, f"{key}.png")).convert("RGBA")
        cut, lamp = _full_lamp(src, attaches[key][key], bones[key])
        crops[side] = cut
        layout[side] = lamp
        print(f"{key} {cut.size} art={lamp}")

    files: dict[str, tuple[Image.Image, str]] = {
        "saloon_plate.webp": (plate, "webp"),
        "saloon_lamp_l.png": (crops["L"], "png"),
        "saloon_lamp_r.png": (crops["R"], "png"),
    }
    stale = ("saloon_lamp_l.webp", "saloon_lamp_r.webp")
    for dest in SPRITE_DESTS:
        os.makedirs(dest, exist_ok=True)
        for name, (im, fmt) in files.items():
            path = os.path.join(dest, name)
            if fmt == "webp":
                im.save(path, "WEBP", quality=86, method=6)
            else:
                im.save(path, "PNG", optimize=True)
        for name in stale:
            old = os.path.join(dest, name)
            if os.path.exists(old):
                os.remove(old)
        print(f"wrote {dest}")

    _write_ts(layout)


if __name__ == "__main__":
    main()
