"""Bake per-glyph advance ratios for the vendored western webfonts.

Why this exists: the HUD sizes its wells from an ESTIMATE of how wide a string
will render (`FrameMorphHud`, `UiLabel`), because measuring a PIXI.Text before
laying it out would need a second render pass. The old estimate was a flat
`value.length * fontSize * 0.6`, tuned by eye for Segoe UI. Swapping in condensed
faces makes that estimate badly wrong in both directions: a 12-character
currency string over-grows its well, and a wide glyph run clips.

So instead of re-guessing a constant, this reads the real `hmtx` advances out of
the shipped woff2 files (instancing the variable fonts at the weight each role
actually renders at) and writes them to a table the estimator sums per character.

Output: src/game/typographyMetrics.generated.ts
Run:    python tools/make_typography_metrics.py
"""

from __future__ import annotations

import os

from fontTools.ttLib import TTFont
from fontTools.varLib.instancer import instantiateVariableFont

HERE = os.path.dirname(os.path.abspath(__file__))
APP = os.path.dirname(HERE)
FONT_DIR = os.path.join(APP, "static", "assets", "fonts", "webfont")
OUT = os.path.join(APP, "src", "game", "typographyMetrics.generated.ts")

# role -> (woff2 files, weight the role renders at or None for static faces)
# Weights MUST match the fontWeight the typography tokens hand to PIXI.TextStyle.
#
# Both subsets are read per role: the exotic currency symbols the HUD can be
# asked to print (INR / RUB / PHP / KRW signs) live only in latin-ext, so reading
# latin alone left them out of the table and every amount in those currencies
# fell back to the mean advance: an underestimate, the direction that clips.
ROLES = {
	"display": (("rye-400-latin.woff2", "rye-400-latin-ext.woff2"), None),
	"label": (("oswald-var-latin.woff2", "oswald-var-latin-ext.woff2"), 600),
	"value": (("archivo-narrow-var-latin.woff2", "archivo-narrow-var-latin-ext.woff2"), 700),
	"accent": (("special-elite-400-latin.woff2", "special-elite-400-latin-ext.woff2"), None),
}

# Every character the HUD, plaques and hero titles can put on screen: currency
# strings, ways / multiplier counters, free-spin fractions and caps labels.
CHARSET = (
	" 0123456789"
	".,:;/'\"$\u00a3\u00a5\u20ac\u20b9\u20bd\u20b1\u20a9"
	"+-\u00d7%()[]#!?&"
	"ABCDEFGHIJKLMNOPQRSTUVWXYZ"
	"abcdefghijklmnopqrstuvwxyz"
)


def advances(filenames: tuple[str, ...], weight: int | None) -> tuple[dict[str, float], float]:
	out: dict[str, float] = {}
	for filename in filenames:
		font = TTFont(os.path.join(FONT_DIR, filename))
		if weight is not None and "fvar" in font:
			font = instantiateVariableFont(font, {"wght": weight}, inplace=False)
		upem = font["head"].unitsPerEm
		cmap: dict[int, str] = {}
		for table in font["cmap"].tables:
			cmap.update(table.cmap)
		hmtx = font["hmtx"]
		for char in CHARSET:
			if char in out:
				continue
			glyph = cmap.get(ord(char))
			if glyph is None or glyph not in hmtx.metrics:
				continue
			out[char] = round(hmtx[glyph][0] / upem, 4)
	# Ordered by CHARSET so the generated table stays stable across runs
	# regardless of which subset a glyph came from.
	out = {char: out[char] for char in CHARSET if char in out}
	fallback = round(sum(out.values()) / len(out), 4) if out else 0.5
	return out, fallback


def ts_key(char: str) -> str:
	if char == "'":
		return "\"'\""
	if char == '"':
		return "'\"'"
	if ord(char) > 126:
		return f"'\\u{ord(char):04x}'"
	return f"'{char}'"


def main() -> None:
	blocks: list[str] = []
	for role, (filenames, weight) in ROLES.items():
		table, fallback = advances(filenames, weight)
		at = f"@{weight}" if weight else ""
		entries = ",\n\t\t\t".join(f"{ts_key(c)}: {w}" for c, w in table.items())
		blocks.append(
			f"\t// {' + '.join(filenames)}{at}\n"
			f"\t{role}: {{\n"
			f"\t\tfallback: {fallback},\n"
			f"\t\tadvance: {{\n\t\t\t{entries},\n\t\t}},\n"
			f"\t}},"
		)

	body = "\n".join(blocks)
	source = f'''// GENERATED by tools/make_typography_metrics.py - do not edit by hand.
//
// Advance width of each glyph as a fraction of the font size, read straight from
// the shipped woff2 `hmtx` table (variable faces instanced at the weight the
// matching typography role renders at). `estimateTextWidth` in typography.ts
// sums these so HUD wells size to the real string width instead of a guessed
// `length * fontSize * 0.6`.
//
// Re-run whenever a role is repointed at a different family or weight.

export type RoleMetrics = {{
	/** mean advance ratio, used for characters outside the baked set */
	fallback: number;
	advance: Record<string, number>;
}};

export const TYPOGRAPHY_METRICS: Record<'display' | 'label' | 'value' | 'accent', RoleMetrics> = {{
{body}
}};
'''
	with open(OUT, "w", encoding="utf-8", newline="\n") as handle:
		handle.write(source)

	print(f"wrote {os.path.relpath(OUT, APP)}")
	for role, (filenames, weight) in ROLES.items():
		table, fallback = advances(filenames, weight)
		digits = {table[d] for d in "0123456789" if d in table}
		caps = [table[c] for c in "ABCDEFGHIJKLMNOPQRSTUVWXYZ" if c in table]
		missing = "".join(c for c in CHARSET if c not in table)
		print(
			f"  {role:8s} {filenames[0]:34s} w={weight or 400:3d} glyphs={len(table):3d} "
			f"digit={'tabular ' + str(next(iter(digits))) if len(digits) == 1 else 'PROP ' + str(sorted(digits))} "
			f"meanCap={sum(caps) / len(caps):.4f} fallback={fallback}"
		)
		if missing:
			print(f"           MISSING from both subsets: {[hex(ord(c)) for c in missing]}")


if __name__ == "__main__":
	main()
