// GENERATED by game-builder (node game-builder/src/cli.mjs gen-frontend).
// Source of truth: game-builder/config/<game>.config.json. Do not edit by hand.

export const GEN_CHARACTER_LAYOUT: Record<string, number> = {
	"heightScale": 1.28,
	"bottomNudge": 200,
	"leftGap": 6,
	"minWidth": 130,
	"anchorY": 0.95
};

/** Read a character layout number (e.g. bottomNudge) with a fallback default. */
export function charLayoutNum(key: string, fallback: number): number {
	const v = GEN_CHARACTER_LAYOUT?.[key];
	return typeof v === 'number' && Number.isFinite(v) ? v : fallback;
}
