// GENERATED by game-builder (node game-builder/src/cli.mjs gen-frontend).
// Source of truth: game-builder/config/<game>.config.json. Do not edit by hand.

export const GEN_FX: Record<string, any> = {
	"splitTelegraph": {
		"label": "Fluorescent Intake Shot",
		"tag": "intake shot",
		"desc": "MODE intakeShot: buckle / fluorescent tube / clipboard stamp projectiles toward fracture targets. ZERO glass knives / triangle shards / Madam Mirror spit.",
		"mode": "intakeShot",
		"shardsPerTarget": 8,
		"durationMs": 420,
		"colors": [
			"0xf4f1ec",
			"0xc8c4bc",
			"0x8a8680",
			"0x3a3632",
			"0x6b2a28"
		],
		"chipScale": 0.09,
		"strapChance": 0.4,
		"impactRingMs": 110
	},
	"splitShatter": {
		"label": "Padded Wall Tear",
		"tag": "padded tear",
		"desc": "MODE paddedTear: foam chunks + strap strips + buckle plates + fluorescent blackout. ZERO falling glass / ceramic knife shards / haunted-mirror triangles.",
		"mode": "paddedTear",
		"shardsPerCell": 18,
		"durationMs": 720,
		"colors": [
			"0xf4f1ec",
			"0xe8e4dc",
			"0xc8c4bc",
			"0x8a8680",
			"0x5c5854",
			"0x3a3632"
		],
		"gravityScale": 1.6,
		"dustCount": 6
	},
	"mirrorBreak": {
		"label": "Intake Stamp Lock",
		"tag": "stamp lock",
		"desc": "MODE intakeStamp: clipboard intake stamp + fluorescent tube frame + REC brackets. ZERO frost glass observation pane.",
		"mode": "intakeStamp",
		"popMs": 100,
		"holdMs": 420,
		"crackBranches": 0,
		"bezelWidth": 5
	},
	"winLightning": {
		"label": "Padded-Cell Whiteout",
		"desc": "REPLACES lightning+prismatic: fluorescent strobe bands + memory-glitch CRT wipe. No bolts. No prism.",
		"megaWinMultiplier": 8685,
		"hue": 200,
		"size": 2,
		"lightningMs": 1400,
		"prismaticMs": 4570,
		"maxExtraBolts": 40,
		"prismaticIntensity": 5,
		"prismaticSpeed": 1,
		"colors": [
			"#f4f1ec",
			"#c8c4bc",
			"#8a8680",
			"#5c5854"
		],
		"mode": "paddedCellStrobe",
		"strobeMs": 900,
		"glitchMs": 2400,
		"bandCount": 9,
		"scanlineCount": 22,
		"flashPeak": 0.85,
		"blackoutChance": 0.06
	},
	"winSweep": {
		"label": "Memory Glitch Wipe",
		"desc": "Horizontal CRT tear across winning cells. Not plasma wash.",
		"reelStagger": 0.14,
		"baseMs": 380,
		"perReelMs": 90,
		"mode": "memoryGlitch",
		"bandCount": 5
	},
	"winDim": {
		"label": "Cell Isolation Dim",
		"desc": "Padded-cell darkness on non-winners + horizontal fluorescent observation lamp scan. NOT diagonal glass glint.",
		"dimAlpha": 0.86,
		"mode": "observationScan",
		"scanMs": 420
	},
	"apparition": {
		"label": "Observation Fracture",
		"tag": "fracture cell",
		"desc": "MODE observationFracture: corner brackets + restraint straps + stamped count. Clinical silver panes on win — NOT haunt halo.",
		"mode": "observationFracture",
		"winGrow": 1.16
	},
	"splitAnimation": {
		"label": "Fluorescent Tear Fracture",
		"tag": "cell split",
		"desc": "MODE fluorescentTear: fluorescent scan cut, intake stamp flare, padded perforation tear, pane snap. ZERO glass/knife blades.",
		"mode": "fluorescentTear",
		"cutMs": 130,
		"cutStagger": 0.1,
		"flareInMs": 16,
		"flareOutMs": 200,
		"detonationMs": 360,
		"paneSnapMs": 180,
		"pulseScale": 1.5,
		"pulseMs": 480,
		"shakeBase": 12,
		"shakePerCell": 3,
		"shakeMax": 22,
		"shakeMs": 280,
		"bladeSparks": 8,
		"seamSparks": 12
	},
	"plasmaLiner": {
		"label": "Restraint Strap Liner",
		"desc": "REPLACES flame: dashed leather straps, steel buckles, ceramic dust. No licking fire.",
		"igniteStagger": 0.06,
		"igniteFlash": 0.18,
		"cornerRadius": 8,
		"fadeInMs": 70,
		"fadeOutMs": 200,
		"flameHeightMin": 4,
		"flameHeightMax": 18,
		"lickScale": 2.8,
		"lickEvery": 7,
		"upBias": 0.55,
		"colors": [
			"0x3a3632",
			"0x8a8680",
			"0xc8c4bc",
			"0xf4f1ec",
			"0x6b2a28"
		],
		"mode": "restraintStraps",
		"strapWidth": 5,
		"dashLen": 18,
		"gapLen": 10,
		"buckleEvery": 6,
		"dustCount": 14
	},
	"framePlasma": {
		"label": "Fluorescent Tube Frame",
		"desc": "REPLACES flame ring: segmented fluorescent tubes with flicker and blackouts.",
		"envelopeMs": 280,
		"flameHeightMin": 7,
		"flameHeightMax": 30,
		"lickScale": 2.5,
		"lickEvery": 7,
		"upBias": 0.5,
		"inset": 3,
		"marginScale": 0.12,
		"colors": [
			"0x3a3632",
			"0x8a8680",
			"0xc8c4bc",
			"0xf4f1ec"
		],
		"mode": "fluorescentTubes",
		"tubeWidth": 6,
		"flickerHz": 11,
		"segmentGap": 14,
		"blackoutChance": 0.05
	},
	"symbolBorder": {
		"label": "High Symbol Outline Frame",
		"tag": "symbols",
		"desc": "Dedicated UI sprite symbolOutlineFrame (padded/steel observation bezel) over high (H*) symbols. NOT Graphics strokes; NOT baked into card art. alpha/scale tune the sprite.",
		"alpha": 1,
		"scale": 1,
		"swatchNames": [],
		"colors": []
	},
	"cellSeal": {
		"label": "Cell Seal Expand",
		"tag": "cell seal",
		"desc": "Observation-pane bezel + restraint brackets + fluorescent tube glow + stamped ceramic ways plaque. Link = Observation Conduit Handshake (housing/couplers/buckles/CCTV scan). Feature name OFF. NO arcade yellow/flower/dots.",
		"highlightMs": 420,
		"expandMs": 720,
		"swatchNames": [
			"bezel steel",
			"frost rim",
			"fluorescent",
			"plaque face",
			"blood stamp",
			"mult text"
		],
		"colors": [
			"0x8a8680",
			"0xc8c4bc",
			"0xf4f1ec",
			"0x2a2826",
			"0x6b2a28",
			"0xf4f1ec"
		],
		"showFeatureLabel": 0,
		"mode": "observationPane",
		"bezelWidth": 5,
		"bracketLen": 22,
		"bracketWidth": 3.2,
		"tubeGlow": 0.55,
		"scanlineCount": 4,
		"badgeScale": 1.2,
		"connectionMode": "observationConduitHandshake",
		"conduitHousingH": 12,
		"conduitScanSpeed": 0.72,
		"conduitBuckleCount": 4
	},
	"winAmountFont": {
		"label": "Win Amount Font",
		"tag": "win text",
		"desc": "PER-GAME FONT (must be unique). Player-facing win/outro/celebration amounts + PRESS ANYWHERE chrome. fontFamily = BitmapText face (clinical = White Room whiteRoomFont). BANNED defaults: silver (Mining-Mayhem western slab template), gold/amethyst/ghost (Madam drip). colors[0] = Pixi tint. Regen: regenerate_assets scope=fonts.",
		"fontFamily": "clinical",
		"fontSizeScale": 1,
		"swatchNames": [
			"tint"
		],
		"colors": [
			"0xf4f1ec"
		]
	}
};

/** Read a numeric FX param with a fallback default. */
export function fxNum(effect: string, key: string, fallback: number): number {
	const v = GEN_FX?.[effect]?.[key];
	return typeof v === 'number' && Number.isFinite(v) ? v : fallback;
}

/** Read a string-array FX param (e.g. CSS colors) with a fallback default. */
export function fxArr(effect: string, key: string, fallback: string[]): string[] {
	const v = GEN_FX?.[effect]?.[key];
	return Array.isArray(v) && v.length ? v.map(String) : fallback;
}

/** Read a color-array FX param as pixi numeric colors (accepts "0xRRGGBB" / "#RRGGBB"). */
export function fxColors(effect: string, key: string, fallback: number[]): number[] {
	const v = GEN_FX?.[effect]?.[key];
	if (!Array.isArray(v) || !v.length) return fallback;
	const nums = v.map((c: unknown) => Number(String(c).replace('#', '0x')));
	return nums.every((n: number) => Number.isFinite(n)) ? nums : fallback;
}

/** Read a string FX param (e.g. fontFamily / mode) with a fallback default. */
export function fxStr(effect: string, key: string, fallback: string): string {
	const v = GEN_FX?.[effect]?.[key];
	return typeof v === 'string' && v ? v : fallback;
}
